<?php



/**
 * This class defines the structure of the 'respuesta_encuesta' table.
 *
 *
 * This class was autogenerated by Propel 1.5.6 on:
 *
 * Wed Mar 12 10:33:15 2014
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    propel.generator.lib.model.map
 */
class RespuestaEncuestaTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.RespuestaEncuestaTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('respuesta_encuesta');
		$this->setPhpName('RespuestaEncuesta');
		$this->setClassname('RespuestaEncuesta');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(true);
		$this->setPrimaryKeyMethodInfo('respuesta_encuesta_id_seq');
		// columns
		$this->addPrimaryKey('ID', 'Id', 'INTEGER', true, null, null);
		$this->addColumn('NUMERO_ENCUESTA', 'NumeroEncuesta', 'INTEGER', false, null, null);
		$this->addColumn('FECHA', 'Fecha', 'DATE', false, null, null);
		$this->addColumn('OBSERVACION', 'Observacion', 'VARCHAR', false, 255, null);
		$this->addColumn('NOMBRE', 'Nombre', 'VARCHAR', false, 255, null);
		$this->addColumn('APELLIDO', 'Apellido', 'VARCHAR', false, 255, null);
		$this->addColumn('TELEFONO', 'Telefono', 'VARCHAR', false, 255, null);
		$this->addColumn('EMAIL', 'Email', 'VARCHAR', false, 255, null);
		$this->addForeignKey('ID_ENCUESTA', 'IdEncuesta', 'BIGINT', 'encuesta', 'ID', false, null, null);
		$this->addColumn('HORA', 'Hora', 'TIME', false, null, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
    $this->addRelation('Encuesta', 'Encuesta', RelationMap::MANY_TO_ONE, array('id_encuesta' => 'id', ), null, null);
    $this->addRelation('RespuestaItem', 'RespuestaItem', RelationMap::ONE_TO_MANY, array('id' => 'id_respuesta_encuesta', ), null, null);
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
		);
	} // getBehaviors()

} // RespuestaEncuestaTableMap
