<?php


/**
 * Base class that represents a query for the 'tipoautor' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.5.6 on:
 *
 * Thu Feb 20 13:36:21 2014
 *
 * @method     TipoautorQuery orderById($order = Criteria::ASC) Order by the id column
 * @method     TipoautorQuery orderByDescripcion($order = Criteria::ASC) Order by the descripcion column
 *
 * @method     TipoautorQuery groupById() Group by the id column
 * @method     TipoautorQuery groupByDescripcion() Group by the descripcion column
 *
 * @method     TipoautorQuery leftJoin($relation) Adds a LEFT JOIN clause to the query
 * @method     TipoautorQuery rightJoin($relation) Adds a RIGHT JOIN clause to the query
 * @method     TipoautorQuery innerJoin($relation) Adds a INNER JOIN clause to the query
 *
 * @method     Tipoautor findOne(PropelPDO $con = null) Return the first Tipoautor matching the query
 * @method     Tipoautor findOneOrCreate(PropelPDO $con = null) Return the first Tipoautor matching the query, or a new Tipoautor object populated from the query conditions when no match is found
 *
 * @method     Tipoautor findOneById(string $id) Return the first Tipoautor filtered by the id column
 * @method     Tipoautor findOneByDescripcion(string $descripcion) Return the first Tipoautor filtered by the descripcion column
 *
 * @method     array findById(string $id) Return Tipoautor objects filtered by the id column
 * @method     array findByDescripcion(string $descripcion) Return Tipoautor objects filtered by the descripcion column
 *
 * @package    propel.generator.lib.model.om
 */
abstract class BaseTipoautorQuery extends ModelCriteria
{

	/**
	 * Initializes internal state of BaseTipoautorQuery object.
	 *
	 * @param     string $dbName The dabase name
	 * @param     string $modelName The phpName of a model, e.g. 'Book'
	 * @param     string $modelAlias The alias for the model in this query, e.g. 'b'
	 */
	public function __construct($dbName = 'propel', $modelName = 'Tipoautor', $modelAlias = null)
	{
		parent::__construct($dbName, $modelName, $modelAlias);
	}

	/**
	 * Returns a new TipoautorQuery object.
	 *
	 * @param     string $modelAlias The alias of a model in the query
	 * @param     Criteria $criteria Optional Criteria to build the query from
	 *
	 * @return    TipoautorQuery
	 */
	public static function create($modelAlias = null, $criteria = null)
	{
		if ($criteria instanceof TipoautorQuery) {
			return $criteria;
		}
		$query = new TipoautorQuery();
		if (null !== $modelAlias) {
			$query->setModelAlias($modelAlias);
		}
		if ($criteria instanceof Criteria) {
			$query->mergeWith($criteria);
		}
		return $query;
	}

	/**
	 * Find object by primary key
	 * Use instance pooling to avoid a database query if the object exists
	 * <code>
	 * $obj  = $c->findPk(12, $con);
	 * </code>
	 * @param     mixed $key Primary key to use for the query
	 * @param     PropelPDO $con an optional connection object
	 *
	 * @return    Tipoautor|array|mixed the result, formatted by the current formatter
	 */
	public function findPk($key, $con = null)
	{
		if ((null !== ($obj = TipoautorPeer::getInstanceFromPool((string) $key))) && $this->getFormatter()->isObjectFormatter()) {
			// the object is alredy in the instance pool
			return $obj;
		} else {
			// the object has not been requested yet, or the formatter is not an object formatter
			$criteria = $this->isKeepQuery() ? clone $this : $this;
			$stmt = $criteria
				->filterByPrimaryKey($key)
				->getSelectStatement($con);
			return $criteria->getFormatter()->init($criteria)->formatOne($stmt);
		}
	}

	/**
	 * Find objects by primary key
	 * <code>
	 * $objs = $c->findPks(array(12, 56, 832), $con);
	 * </code>
	 * @param     array $keys Primary keys to use for the query
	 * @param     PropelPDO $con an optional connection object
	 *
	 * @return    PropelObjectCollection|array|mixed the list of results, formatted by the current formatter
	 */
	public function findPks($keys, $con = null)
	{	
		$criteria = $this->isKeepQuery() ? clone $this : $this;
		return $this
			->filterByPrimaryKeys($keys)
			->find($con);
	}

	/**
	 * Filter the query by primary key
	 *
	 * @param     mixed $key Primary key to use for the query
	 *
	 * @return    TipoautorQuery The current query, for fluid interface
	 */
	public function filterByPrimaryKey($key)
	{
		return $this->addUsingAlias(TipoautorPeer::ID, $key, Criteria::EQUAL);
	}

	/**
	 * Filter the query by a list of primary keys
	 *
	 * @param     array $keys The list of primary key to use for the query
	 *
	 * @return    TipoautorQuery The current query, for fluid interface
	 */
	public function filterByPrimaryKeys($keys)
	{
		return $this->addUsingAlias(TipoautorPeer::ID, $keys, Criteria::IN);
	}

	/**
	 * Filter the query on the id column
	 * 
	 * @param     string|array $id The value to use as filter.
	 *            Accepts an associative array('min' => $minValue, 'max' => $maxValue)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    TipoautorQuery The current query, for fluid interface
	 */
	public function filterById($id = null, $comparison = null)
	{
		if (is_array($id) && null === $comparison) {
			$comparison = Criteria::IN;
		}
		return $this->addUsingAlias(TipoautorPeer::ID, $id, $comparison);
	}

	/**
	 * Filter the query on the descripcion column
	 * 
	 * @param     string $descripcion The value to use as filter.
	 *            Accepts wildcards (* and % trigger a LIKE)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    TipoautorQuery The current query, for fluid interface
	 */
	public function filterByDescripcion($descripcion = null, $comparison = null)
	{
		if (null === $comparison) {
			if (is_array($descripcion)) {
				$comparison = Criteria::IN;
			} elseif (preg_match('/[\%\*]/', $descripcion)) {
				$descripcion = str_replace('*', '%', $descripcion);
				$comparison = Criteria::LIKE;
			}
		}
		return $this->addUsingAlias(TipoautorPeer::DESCRIPCION, $descripcion, $comparison);
	}

	/**
	 * Exclude object from result
	 *
	 * @param     Tipoautor $tipoautor Object to remove from the list of results
	 *
	 * @return    TipoautorQuery The current query, for fluid interface
	 */
	public function prune($tipoautor = null)
	{
		if ($tipoautor) {
			$this->addUsingAlias(TipoautorPeer::ID, $tipoautor->getId(), Criteria::NOT_EQUAL);
	  }
	  
		return $this;
	}

} // BaseTipoautorQuery
