<?php


/**
 * Base class that represents a row from the 'impresion' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.5.6 on:
 *
 * Thu Feb 20 13:36:21 2014
 *
 * @package    propel.generator.lib.model.om
 */
abstract class BaseImpresion extends BaseObject  implements Persistent
{

	/**
	 * Peer class name
	 */
	const PEER = 'ImpresionPeer';

	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        ImpresionPeer
	 */
	protected static $peer;

	/**
	 * The value for the id field.
	 * @var        string
	 */
	protected $id;

	/**
	 * The value for the volumen field.
	 * @var        int
	 */
	protected $volumen;

	/**
	 * The value for the id_edicion field.
	 * @var        int
	 */
	protected $id_edicion;

	/**
	 * The value for the id_tipocaratula field.
	 * @var        int
	 */
	protected $id_tipocaratula;

	/**
	 * The value for the id_tipoimpresion field.
	 * @var        int
	 */
	protected $id_tipoimpresion;

	/**
	 * The value for the id_tipoencuadernacion field.
	 * @var        int
	 */
	protected $id_tipoencuadernacion;

	/**
	 * The value for the costo field.
	 * @var        string
	 */
	protected $costo;

	/**
	 * The value for the id_tipotripa field.
	 * @var        int
	 */
	protected $id_tipotripa;

	/**
	 * @var        Edicion
	 */
	protected $aEdicion;

	/**
	 * @var        Tipocaratula
	 */
	protected $aTipocaratula;

	/**
	 * @var        Tipoimpresion
	 */
	protected $aTipoimpresion;

	/**
	 * @var        Tipoencuadernacion
	 */
	protected $aTipoencuadernacion;

	/**
	 * @var        Tipotripa
	 */
	protected $aTipotripa;

	/**
	 * @var        array Historico[] Collection to store aggregation of Historico objects.
	 */
	protected $collHistoricos;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	/**
	 * Get the [id] column value.
	 * 
	 * @return     string
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Get the [volumen] column value.
	 * 
	 * @return     int
	 */
	public function getVolumen()
	{
		return $this->volumen;
	}

	/**
	 * Get the [id_edicion] column value.
	 * 
	 * @return     int
	 */
	public function getIdEdicion()
	{
		return $this->id_edicion;
	}

	/**
	 * Get the [id_tipocaratula] column value.
	 * 
	 * @return     int
	 */
	public function getIdTipocaratula()
	{
		return $this->id_tipocaratula;
	}

	/**
	 * Get the [id_tipoimpresion] column value.
	 * 
	 * @return     int
	 */
	public function getIdTipoimpresion()
	{
		return $this->id_tipoimpresion;
	}

	/**
	 * Get the [id_tipoencuadernacion] column value.
	 * 
	 * @return     int
	 */
	public function getIdTipoencuadernacion()
	{
		return $this->id_tipoencuadernacion;
	}

	/**
	 * Get the [costo] column value.
	 * 
	 * @return     string
	 */
	public function getCosto()
	{
		return $this->costo;
	}

	/**
	 * Get the [id_tipotripa] column value.
	 * 
	 * @return     int
	 */
	public function getIdTipotripa()
	{
		return $this->id_tipotripa;
	}

	/**
	 * Set the value of [id] column.
	 * 
	 * @param      string $v new value
	 * @return     Impresion The current object (for fluent API support)
	 */
	public function setId($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->id !== $v) {
			$this->id = $v;
			$this->modifiedColumns[] = ImpresionPeer::ID;
		}

		return $this;
	} // setId()

	/**
	 * Set the value of [volumen] column.
	 * 
	 * @param      int $v new value
	 * @return     Impresion The current object (for fluent API support)
	 */
	public function setVolumen($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->volumen !== $v) {
			$this->volumen = $v;
			$this->modifiedColumns[] = ImpresionPeer::VOLUMEN;
		}

		return $this;
	} // setVolumen()

	/**
	 * Set the value of [id_edicion] column.
	 * 
	 * @param      int $v new value
	 * @return     Impresion The current object (for fluent API support)
	 */
	public function setIdEdicion($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id_edicion !== $v) {
			$this->id_edicion = $v;
			$this->modifiedColumns[] = ImpresionPeer::ID_EDICION;
		}

		if ($this->aEdicion !== null && $this->aEdicion->getId() !== $v) {
			$this->aEdicion = null;
		}

		return $this;
	} // setIdEdicion()

	/**
	 * Set the value of [id_tipocaratula] column.
	 * 
	 * @param      int $v new value
	 * @return     Impresion The current object (for fluent API support)
	 */
	public function setIdTipocaratula($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id_tipocaratula !== $v) {
			$this->id_tipocaratula = $v;
			$this->modifiedColumns[] = ImpresionPeer::ID_TIPOCARATULA;
		}

		if ($this->aTipocaratula !== null && $this->aTipocaratula->getId() !== $v) {
			$this->aTipocaratula = null;
		}

		return $this;
	} // setIdTipocaratula()

	/**
	 * Set the value of [id_tipoimpresion] column.
	 * 
	 * @param      int $v new value
	 * @return     Impresion The current object (for fluent API support)
	 */
	public function setIdTipoimpresion($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id_tipoimpresion !== $v) {
			$this->id_tipoimpresion = $v;
			$this->modifiedColumns[] = ImpresionPeer::ID_TIPOIMPRESION;
		}

		if ($this->aTipoimpresion !== null && $this->aTipoimpresion->getId() !== $v) {
			$this->aTipoimpresion = null;
		}

		return $this;
	} // setIdTipoimpresion()

	/**
	 * Set the value of [id_tipoencuadernacion] column.
	 * 
	 * @param      int $v new value
	 * @return     Impresion The current object (for fluent API support)
	 */
	public function setIdTipoencuadernacion($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id_tipoencuadernacion !== $v) {
			$this->id_tipoencuadernacion = $v;
			$this->modifiedColumns[] = ImpresionPeer::ID_TIPOENCUADERNACION;
		}

		if ($this->aTipoencuadernacion !== null && $this->aTipoencuadernacion->getId() !== $v) {
			$this->aTipoencuadernacion = null;
		}

		return $this;
	} // setIdTipoencuadernacion()

	/**
	 * Set the value of [costo] column.
	 * 
	 * @param      string $v new value
	 * @return     Impresion The current object (for fluent API support)
	 */
	public function setCosto($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->costo !== $v) {
			$this->costo = $v;
			$this->modifiedColumns[] = ImpresionPeer::COSTO;
		}

		return $this;
	} // setCosto()

	/**
	 * Set the value of [id_tipotripa] column.
	 * 
	 * @param      int $v new value
	 * @return     Impresion The current object (for fluent API support)
	 */
	public function setIdTipotripa($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id_tipotripa !== $v) {
			$this->id_tipotripa = $v;
			$this->modifiedColumns[] = ImpresionPeer::ID_TIPOTRIPA;
		}

		if ($this->aTipotripa !== null && $this->aTipotripa->getId() !== $v) {
			$this->aTipotripa = null;
		}

		return $this;
	} // setIdTipotripa()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id = ($row[$startcol + 0] !== null) ? (string) $row[$startcol + 0] : null;
			$this->volumen = ($row[$startcol + 1] !== null) ? (int) $row[$startcol + 1] : null;
			$this->id_edicion = ($row[$startcol + 2] !== null) ? (int) $row[$startcol + 2] : null;
			$this->id_tipocaratula = ($row[$startcol + 3] !== null) ? (int) $row[$startcol + 3] : null;
			$this->id_tipoimpresion = ($row[$startcol + 4] !== null) ? (int) $row[$startcol + 4] : null;
			$this->id_tipoencuadernacion = ($row[$startcol + 5] !== null) ? (int) $row[$startcol + 5] : null;
			$this->costo = ($row[$startcol + 6] !== null) ? (string) $row[$startcol + 6] : null;
			$this->id_tipotripa = ($row[$startcol + 7] !== null) ? (int) $row[$startcol + 7] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			return $startcol + 8; // 8 = ImpresionPeer::NUM_COLUMNS - ImpresionPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating Impresion object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->aEdicion !== null && $this->id_edicion !== $this->aEdicion->getId()) {
			$this->aEdicion = null;
		}
		if ($this->aTipocaratula !== null && $this->id_tipocaratula !== $this->aTipocaratula->getId()) {
			$this->aTipocaratula = null;
		}
		if ($this->aTipoimpresion !== null && $this->id_tipoimpresion !== $this->aTipoimpresion->getId()) {
			$this->aTipoimpresion = null;
		}
		if ($this->aTipoencuadernacion !== null && $this->id_tipoencuadernacion !== $this->aTipoencuadernacion->getId()) {
			$this->aTipoencuadernacion = null;
		}
		if ($this->aTipotripa !== null && $this->id_tipotripa !== $this->aTipotripa->getId()) {
			$this->aTipotripa = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(ImpresionPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = ImpresionPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->aEdicion = null;
			$this->aTipocaratula = null;
			$this->aTipoimpresion = null;
			$this->aTipoencuadernacion = null;
			$this->aTipotripa = null;
			$this->collHistoricos = null;

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(ImpresionPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		$con->beginTransaction();
		try {
			$ret = $this->preDelete($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseImpresion:delete:pre') as $callable)
			{
			  if (call_user_func($callable, $this, $con))
			  {
			    $con->commit();
			    return;
			  }
			}

			if ($ret) {
				ImpresionQuery::create()
					->filterByPrimaryKey($this->getPrimaryKey())
					->delete($con);
				$this->postDelete($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseImpresion:delete:post') as $callable)
				{
				  call_user_func($callable, $this, $con);
				}

				$con->commit();
				$this->setDeleted(true);
			} else {
				$con->commit();
			}
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(ImpresionPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		$con->beginTransaction();
		$isInsert = $this->isNew();
		try {
			$ret = $this->preSave($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseImpresion:save:pre') as $callable)
			{
			  if (is_integer($affectedRows = call_user_func($callable, $this, $con)))
			  {
			  	$con->commit();
			    return $affectedRows;
			  }
			}

			if ($isInsert) {
				$ret = $ret && $this->preInsert($con);
			} else {
				$ret = $ret && $this->preUpdate($con);
			}
			if ($ret) {
				$affectedRows = $this->doSave($con);
				if ($isInsert) {
					$this->postInsert($con);
				} else {
					$this->postUpdate($con);
				}
				$this->postSave($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseImpresion:save:post') as $callable)
				{
				  call_user_func($callable, $this, $con, $affectedRows);
				}

				ImpresionPeer::addInstanceToPool($this);
			} else {
				$affectedRows = 0;
			}
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aEdicion !== null) {
				if ($this->aEdicion->isModified() || $this->aEdicion->isNew()) {
					$affectedRows += $this->aEdicion->save($con);
				}
				$this->setEdicion($this->aEdicion);
			}

			if ($this->aTipocaratula !== null) {
				if ($this->aTipocaratula->isModified() || $this->aTipocaratula->isNew()) {
					$affectedRows += $this->aTipocaratula->save($con);
				}
				$this->setTipocaratula($this->aTipocaratula);
			}

			if ($this->aTipoimpresion !== null) {
				if ($this->aTipoimpresion->isModified() || $this->aTipoimpresion->isNew()) {
					$affectedRows += $this->aTipoimpresion->save($con);
				}
				$this->setTipoimpresion($this->aTipoimpresion);
			}

			if ($this->aTipoencuadernacion !== null) {
				if ($this->aTipoencuadernacion->isModified() || $this->aTipoencuadernacion->isNew()) {
					$affectedRows += $this->aTipoencuadernacion->save($con);
				}
				$this->setTipoencuadernacion($this->aTipoencuadernacion);
			}

			if ($this->aTipotripa !== null) {
				if ($this->aTipotripa->isModified() || $this->aTipotripa->isNew()) {
					$affectedRows += $this->aTipotripa->save($con);
				}
				$this->setTipotripa($this->aTipotripa);
			}

			if ($this->isNew() ) {
				$this->modifiedColumns[] = ImpresionPeer::ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$criteria = $this->buildCriteria();
					if ($criteria->keyContainsValue(ImpresionPeer::ID) ) {
						throw new PropelException('Cannot insert a value for auto-increment primary key ('.ImpresionPeer::ID.')');
					}

					$pk = BasePeer::doInsert($criteria, $con);
					$affectedRows += 1;
					$this->setId($pk);  //[IMV] update autoincrement primary key
					$this->setNew(false);
				} else {
					$affectedRows += ImpresionPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			if ($this->collHistoricos !== null) {
				foreach ($this->collHistoricos as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aEdicion !== null) {
				if (!$this->aEdicion->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aEdicion->getValidationFailures());
				}
			}

			if ($this->aTipocaratula !== null) {
				if (!$this->aTipocaratula->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aTipocaratula->getValidationFailures());
				}
			}

			if ($this->aTipoimpresion !== null) {
				if (!$this->aTipoimpresion->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aTipoimpresion->getValidationFailures());
				}
			}

			if ($this->aTipoencuadernacion !== null) {
				if (!$this->aTipoencuadernacion->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aTipoencuadernacion->getValidationFailures());
				}
			}

			if ($this->aTipotripa !== null) {
				if (!$this->aTipotripa->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aTipotripa->getValidationFailures());
				}
			}


			if (($retval = ImpresionPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}


				if ($this->collHistoricos !== null) {
					foreach ($this->collHistoricos as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}


			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = ImpresionPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getId();
				break;
			case 1:
				return $this->getVolumen();
				break;
			case 2:
				return $this->getIdEdicion();
				break;
			case 3:
				return $this->getIdTipocaratula();
				break;
			case 4:
				return $this->getIdTipoimpresion();
				break;
			case 5:
				return $this->getIdTipoencuadernacion();
				break;
			case 6:
				return $this->getCosto();
				break;
			case 7:
				return $this->getIdTipotripa();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param     string  $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 *                    BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 *                    Defaults to BasePeer::TYPE_PHPNAME.
	 * @param     boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns. Defaults to TRUE.
	 * @param     boolean $includeForeignObjects (optional) Whether to include hydrated related objects. Default to FALSE.
	 *
	 * @return    array an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true, $includeForeignObjects = false)
	{
		$keys = ImpresionPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getId(),
			$keys[1] => $this->getVolumen(),
			$keys[2] => $this->getIdEdicion(),
			$keys[3] => $this->getIdTipocaratula(),
			$keys[4] => $this->getIdTipoimpresion(),
			$keys[5] => $this->getIdTipoencuadernacion(),
			$keys[6] => $this->getCosto(),
			$keys[7] => $this->getIdTipotripa(),
		);
		if ($includeForeignObjects) {
			if (null !== $this->aEdicion) {
				$result['Edicion'] = $this->aEdicion->toArray($keyType, $includeLazyLoadColumns, true);
			}
			if (null !== $this->aTipocaratula) {
				$result['Tipocaratula'] = $this->aTipocaratula->toArray($keyType, $includeLazyLoadColumns, true);
			}
			if (null !== $this->aTipoimpresion) {
				$result['Tipoimpresion'] = $this->aTipoimpresion->toArray($keyType, $includeLazyLoadColumns, true);
			}
			if (null !== $this->aTipoencuadernacion) {
				$result['Tipoencuadernacion'] = $this->aTipoencuadernacion->toArray($keyType, $includeLazyLoadColumns, true);
			}
			if (null !== $this->aTipotripa) {
				$result['Tipotripa'] = $this->aTipotripa->toArray($keyType, $includeLazyLoadColumns, true);
			}
		}
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = ImpresionPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setId($value);
				break;
			case 1:
				$this->setVolumen($value);
				break;
			case 2:
				$this->setIdEdicion($value);
				break;
			case 3:
				$this->setIdTipocaratula($value);
				break;
			case 4:
				$this->setIdTipoimpresion($value);
				break;
			case 5:
				$this->setIdTipoencuadernacion($value);
				break;
			case 6:
				$this->setCosto($value);
				break;
			case 7:
				$this->setIdTipotripa($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = ImpresionPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setVolumen($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setIdEdicion($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setIdTipocaratula($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setIdTipoimpresion($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setIdTipoencuadernacion($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setCosto($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setIdTipotripa($arr[$keys[7]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(ImpresionPeer::DATABASE_NAME);

		if ($this->isColumnModified(ImpresionPeer::ID)) $criteria->add(ImpresionPeer::ID, $this->id);
		if ($this->isColumnModified(ImpresionPeer::VOLUMEN)) $criteria->add(ImpresionPeer::VOLUMEN, $this->volumen);
		if ($this->isColumnModified(ImpresionPeer::ID_EDICION)) $criteria->add(ImpresionPeer::ID_EDICION, $this->id_edicion);
		if ($this->isColumnModified(ImpresionPeer::ID_TIPOCARATULA)) $criteria->add(ImpresionPeer::ID_TIPOCARATULA, $this->id_tipocaratula);
		if ($this->isColumnModified(ImpresionPeer::ID_TIPOIMPRESION)) $criteria->add(ImpresionPeer::ID_TIPOIMPRESION, $this->id_tipoimpresion);
		if ($this->isColumnModified(ImpresionPeer::ID_TIPOENCUADERNACION)) $criteria->add(ImpresionPeer::ID_TIPOENCUADERNACION, $this->id_tipoencuadernacion);
		if ($this->isColumnModified(ImpresionPeer::COSTO)) $criteria->add(ImpresionPeer::COSTO, $this->costo);
		if ($this->isColumnModified(ImpresionPeer::ID_TIPOTRIPA)) $criteria->add(ImpresionPeer::ID_TIPOTRIPA, $this->id_tipotripa);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(ImpresionPeer::DATABASE_NAME);
		$criteria->add(ImpresionPeer::ID, $this->id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     string
	 */
	public function getPrimaryKey()
	{
		return $this->getId();
	}

	/**
	 * Generic method to set the primary key (id column).
	 *
	 * @param      string $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setId($key);
	}

	/**
	 * Returns true if the primary key for this object is null.
	 * @return     boolean
	 */
	public function isPrimaryKeyNull()
	{
		return null === $this->getId();
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of Impresion (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{
		$copyObj->setVolumen($this->volumen);
		$copyObj->setIdEdicion($this->id_edicion);
		$copyObj->setIdTipocaratula($this->id_tipocaratula);
		$copyObj->setIdTipoimpresion($this->id_tipoimpresion);
		$copyObj->setIdTipoencuadernacion($this->id_tipoencuadernacion);
		$copyObj->setCosto($this->costo);
		$copyObj->setIdTipotripa($this->id_tipotripa);

		if ($deepCopy) {
			// important: temporarily setNew(false) because this affects the behavior of
			// the getter/setter methods for fkey referrer objects.
			$copyObj->setNew(false);

			foreach ($this->getHistoricos() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addHistorico($relObj->copy($deepCopy));
				}
			}

		} // if ($deepCopy)


		$copyObj->setNew(true);
		$copyObj->setId(NULL); // this is a auto-increment column, so set to default value
	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     Impresion Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     ImpresionPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new ImpresionPeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a Edicion object.
	 *
	 * @param      Edicion $v
	 * @return     Impresion The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setEdicion(Edicion $v = null)
	{
		if ($v === null) {
			$this->setIdEdicion(NULL);
		} else {
			$this->setIdEdicion($v->getId());
		}

		$this->aEdicion = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Edicion object, it will not be re-added.
		if ($v !== null) {
			$v->addImpresion($this);
		}

		return $this;
	}


	/**
	 * Get the associated Edicion object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Edicion The associated Edicion object.
	 * @throws     PropelException
	 */
	public function getEdicion(PropelPDO $con = null)
	{
		if ($this->aEdicion === null && ($this->id_edicion !== null)) {
			$this->aEdicion = EdicionQuery::create()->findPk($this->id_edicion, $con);
			/* The following can be used additionally to
				 guarantee the related object contains a reference
				 to this object.  This level of coupling may, however, be
				 undesirable since it could result in an only partially populated collection
				 in the referenced object.
				 $this->aEdicion->addImpresions($this);
			 */
		}
		return $this->aEdicion;
	}

	/**
	 * Declares an association between this object and a Tipocaratula object.
	 *
	 * @param      Tipocaratula $v
	 * @return     Impresion The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setTipocaratula(Tipocaratula $v = null)
	{
		if ($v === null) {
			$this->setIdTipocaratula(NULL);
		} else {
			$this->setIdTipocaratula($v->getId());
		}

		$this->aTipocaratula = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Tipocaratula object, it will not be re-added.
		if ($v !== null) {
			$v->addImpresion($this);
		}

		return $this;
	}


	/**
	 * Get the associated Tipocaratula object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Tipocaratula The associated Tipocaratula object.
	 * @throws     PropelException
	 */
	public function getTipocaratula(PropelPDO $con = null)
	{
		if ($this->aTipocaratula === null && ($this->id_tipocaratula !== null)) {
			$this->aTipocaratula = TipocaratulaQuery::create()->findPk($this->id_tipocaratula, $con);
			/* The following can be used additionally to
				 guarantee the related object contains a reference
				 to this object.  This level of coupling may, however, be
				 undesirable since it could result in an only partially populated collection
				 in the referenced object.
				 $this->aTipocaratula->addImpresions($this);
			 */
		}
		return $this->aTipocaratula;
	}

	/**
	 * Declares an association between this object and a Tipoimpresion object.
	 *
	 * @param      Tipoimpresion $v
	 * @return     Impresion The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setTipoimpresion(Tipoimpresion $v = null)
	{
		if ($v === null) {
			$this->setIdTipoimpresion(NULL);
		} else {
			$this->setIdTipoimpresion($v->getId());
		}

		$this->aTipoimpresion = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Tipoimpresion object, it will not be re-added.
		if ($v !== null) {
			$v->addImpresion($this);
		}

		return $this;
	}


	/**
	 * Get the associated Tipoimpresion object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Tipoimpresion The associated Tipoimpresion object.
	 * @throws     PropelException
	 */
	public function getTipoimpresion(PropelPDO $con = null)
	{
		if ($this->aTipoimpresion === null && ($this->id_tipoimpresion !== null)) {
			$this->aTipoimpresion = TipoimpresionQuery::create()->findPk($this->id_tipoimpresion, $con);
			/* The following can be used additionally to
				 guarantee the related object contains a reference
				 to this object.  This level of coupling may, however, be
				 undesirable since it could result in an only partially populated collection
				 in the referenced object.
				 $this->aTipoimpresion->addImpresions($this);
			 */
		}
		return $this->aTipoimpresion;
	}

	/**
	 * Declares an association between this object and a Tipoencuadernacion object.
	 *
	 * @param      Tipoencuadernacion $v
	 * @return     Impresion The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setTipoencuadernacion(Tipoencuadernacion $v = null)
	{
		if ($v === null) {
			$this->setIdTipoencuadernacion(NULL);
		} else {
			$this->setIdTipoencuadernacion($v->getId());
		}

		$this->aTipoencuadernacion = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Tipoencuadernacion object, it will not be re-added.
		if ($v !== null) {
			$v->addImpresion($this);
		}

		return $this;
	}


	/**
	 * Get the associated Tipoencuadernacion object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Tipoencuadernacion The associated Tipoencuadernacion object.
	 * @throws     PropelException
	 */
	public function getTipoencuadernacion(PropelPDO $con = null)
	{
		if ($this->aTipoencuadernacion === null && ($this->id_tipoencuadernacion !== null)) {
			$this->aTipoencuadernacion = TipoencuadernacionQuery::create()->findPk($this->id_tipoencuadernacion, $con);
			/* The following can be used additionally to
				 guarantee the related object contains a reference
				 to this object.  This level of coupling may, however, be
				 undesirable since it could result in an only partially populated collection
				 in the referenced object.
				 $this->aTipoencuadernacion->addImpresions($this);
			 */
		}
		return $this->aTipoencuadernacion;
	}

	/**
	 * Declares an association between this object and a Tipotripa object.
	 *
	 * @param      Tipotripa $v
	 * @return     Impresion The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setTipotripa(Tipotripa $v = null)
	{
		if ($v === null) {
			$this->setIdTipotripa(NULL);
		} else {
			$this->setIdTipotripa($v->getId());
		}

		$this->aTipotripa = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Tipotripa object, it will not be re-added.
		if ($v !== null) {
			$v->addImpresion($this);
		}

		return $this;
	}


	/**
	 * Get the associated Tipotripa object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Tipotripa The associated Tipotripa object.
	 * @throws     PropelException
	 */
	public function getTipotripa(PropelPDO $con = null)
	{
		if ($this->aTipotripa === null && ($this->id_tipotripa !== null)) {
			$this->aTipotripa = TipotripaQuery::create()->findPk($this->id_tipotripa, $con);
			/* The following can be used additionally to
				 guarantee the related object contains a reference
				 to this object.  This level of coupling may, however, be
				 undesirable since it could result in an only partially populated collection
				 in the referenced object.
				 $this->aTipotripa->addImpresions($this);
			 */
		}
		return $this->aTipotripa;
	}

	/**
	 * Clears out the collHistoricos collection
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addHistoricos()
	 */
	public function clearHistoricos()
	{
		$this->collHistoricos = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collHistoricos collection.
	 *
	 * By default this just sets the collHistoricos collection to an empty array (like clearcollHistoricos());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initHistoricos()
	{
		$this->collHistoricos = new PropelObjectCollection();
		$this->collHistoricos->setModel('Historico');
	}

	/**
	 * Gets an array of Historico objects which contain a foreign key that references this object.
	 *
	 * If the $criteria is not null, it is used to always fetch the results from the database.
	 * Otherwise the results are fetched from the database the first time, then cached.
	 * Next time the same method is called without $criteria, the cached collection is returned.
	 * If this Impresion is new, it will return
	 * an empty collection or the current collection; the criteria is ignored on a new object.
	 *
	 * @param      Criteria $criteria optional Criteria object to narrow the query
	 * @param      PropelPDO $con optional connection object
	 * @return     PropelCollection|array Historico[] List of Historico objects
	 * @throws     PropelException
	 */
	public function getHistoricos($criteria = null, PropelPDO $con = null)
	{
		if(null === $this->collHistoricos || null !== $criteria) {
			if ($this->isNew() && null === $this->collHistoricos) {
				// return empty collection
				$this->initHistoricos();
			} else {
				$collHistoricos = HistoricoQuery::create(null, $criteria)
					->filterByImpresion($this)
					->find($con);
				if (null !== $criteria) {
					return $collHistoricos;
				}
				$this->collHistoricos = $collHistoricos;
			}
		}
		return $this->collHistoricos;
	}

	/**
	 * Returns the number of related Historico objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Historico objects.
	 * @throws     PropelException
	 */
	public function countHistoricos(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if(null === $this->collHistoricos || null !== $criteria) {
			if ($this->isNew() && null === $this->collHistoricos) {
				return 0;
			} else {
				$query = HistoricoQuery::create(null, $criteria);
				if($distinct) {
					$query->distinct();
				}
				return $query
					->filterByImpresion($this)
					->count($con);
			}
		} else {
			return count($this->collHistoricos);
		}
	}

	/**
	 * Method called to associate a Historico object to this object
	 * through the Historico foreign key attribute.
	 *
	 * @param      Historico $l Historico
	 * @return     void
	 * @throws     PropelException
	 */
	public function addHistorico(Historico $l)
	{
		if ($this->collHistoricos === null) {
			$this->initHistoricos();
		}
		if (!$this->collHistoricos->contains($l)) { // only add it if the **same** object is not already associated
			$this->collHistoricos[]= $l;
			$l->setImpresion($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Impresion is new, it will return
	 * an empty collection; or if this Impresion has previously
	 * been saved, it will retrieve related Historicos from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Impresion.
	 *
	 * @param      Criteria $criteria optional Criteria object to narrow the query
	 * @param      PropelPDO $con optional connection object
	 * @param      string $join_behavior optional join type to use (defaults to Criteria::LEFT_JOIN)
	 * @return     PropelCollection|array Historico[] List of Historico objects
	 */
	public function getHistoricosJoinEdicion($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		$query = HistoricoQuery::create(null, $criteria);
		$query->joinWith('Edicion', $join_behavior);

		return $this->getHistoricos($query, $con);
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Impresion is new, it will return
	 * an empty collection; or if this Impresion has previously
	 * been saved, it will retrieve related Historicos from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Impresion.
	 *
	 * @param      Criteria $criteria optional Criteria object to narrow the query
	 * @param      PropelPDO $con optional connection object
	 * @param      string $join_behavior optional join type to use (defaults to Criteria::LEFT_JOIN)
	 * @return     PropelCollection|array Historico[] List of Historico objects
	 */
	public function getHistoricosJoinStatus($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		$query = HistoricoQuery::create(null, $criteria);
		$query->joinWith('Status', $join_behavior);

		return $this->getHistoricos($query, $con);
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Impresion is new, it will return
	 * an empty collection; or if this Impresion has previously
	 * been saved, it will retrieve related Historicos from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Impresion.
	 *
	 * @param      Criteria $criteria optional Criteria object to narrow the query
	 * @param      PropelPDO $con optional connection object
	 * @param      string $join_behavior optional join type to use (defaults to Criteria::LEFT_JOIN)
	 * @return     PropelCollection|array Historico[] List of Historico objects
	 */
	public function getHistoricosJoinInstitucion($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		$query = HistoricoQuery::create(null, $criteria);
		$query->joinWith('Institucion', $join_behavior);

		return $this->getHistoricos($query, $con);
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Impresion is new, it will return
	 * an empty collection; or if this Impresion has previously
	 * been saved, it will retrieve related Historicos from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Impresion.
	 *
	 * @param      Criteria $criteria optional Criteria object to narrow the query
	 * @param      PropelPDO $con optional connection object
	 * @param      string $join_behavior optional join type to use (defaults to Criteria::LEFT_JOIN)
	 * @return     PropelCollection|array Historico[] List of Historico objects
	 */
	public function getHistoricosJoinDistribucion($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		$query = HistoricoQuery::create(null, $criteria);
		$query->joinWith('Distribucion', $join_behavior);

		return $this->getHistoricos($query, $con);
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Impresion is new, it will return
	 * an empty collection; or if this Impresion has previously
	 * been saved, it will retrieve related Historicos from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Impresion.
	 *
	 * @param      Criteria $criteria optional Criteria object to narrow the query
	 * @param      PropelPDO $con optional connection object
	 * @param      string $join_behavior optional join type to use (defaults to Criteria::LEFT_JOIN)
	 * @return     PropelCollection|array Historico[] List of Historico objects
	 */
	public function getHistoricosJoinVenta($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		$query = HistoricoQuery::create(null, $criteria);
		$query->joinWith('Venta', $join_behavior);

		return $this->getHistoricos($query, $con);
	}

	/**
	 * Clears the current object and sets all attributes to their default values
	 */
	public function clear()
	{
		$this->id = null;
		$this->volumen = null;
		$this->id_edicion = null;
		$this->id_tipocaratula = null;
		$this->id_tipoimpresion = null;
		$this->id_tipoencuadernacion = null;
		$this->costo = null;
		$this->id_tipotripa = null;
		$this->alreadyInSave = false;
		$this->alreadyInValidation = false;
		$this->clearAllReferences();
		$this->resetModified();
		$this->setNew(true);
		$this->setDeleted(false);
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
			if ($this->collHistoricos) {
				foreach ((array) $this->collHistoricos as $o) {
					$o->clearAllReferences($deep);
				}
			}
		} // if ($deep)

		$this->collHistoricos = null;
		$this->aEdicion = null;
		$this->aTipocaratula = null;
		$this->aTipoimpresion = null;
		$this->aTipoencuadernacion = null;
		$this->aTipotripa = null;
	}

	/**
	 * Catches calls to virtual methods
	 */
	public function __call($name, $params)
	{
		// symfony_behaviors behavior
		if ($callable = sfMixer::getCallable('BaseImpresion:' . $name))
		{
		  array_unshift($params, $this);
		  return call_user_func_array($callable, $params);
		}

		if (preg_match('/get(\w+)/', $name, $matches)) {
			$virtualColumn = $matches[1];
			if ($this->hasVirtualColumn($virtualColumn)) {
				return $this->getVirtualColumn($virtualColumn);
			}
			// no lcfirst in php<5.3...
			$virtualColumn[0] = strtolower($virtualColumn[0]);
			if ($this->hasVirtualColumn($virtualColumn)) {
				return $this->getVirtualColumn($virtualColumn);
			}
		}
		return parent::__call($name, $params);
	}

} // BaseImpresion
