<?php


/**
 * Base static class for performing query and update operations on the 'tipodestino' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.5.6 on:
 *
 * Thu Feb 20 13:36:21 2014
 *
 * @package    propel.generator.lib.model.om
 */
abstract class BaseTipodestinoPeer {

	/** the default database name for this class */
	const DATABASE_NAME = 'propel';

	/** the table name for this class */
	const TABLE_NAME = 'tipodestino';

	/** the related Propel class for this table */
	const OM_CLASS = 'Tipodestino';

	/** A class that can be returned by this peer. */
	const CLASS_DEFAULT = 'lib.model.Tipodestino';

	/** the related TableMap class for this table */
	const TM_CLASS = 'TipodestinoTableMap';
	
	/** The total number of columns. */
	const NUM_COLUMNS = 12;

	/** The number of lazy-loaded columns. */
	const NUM_LAZY_LOAD_COLUMNS = 0;

	/** the column name for the ID field */
	const ID = 'tipodestino.ID';

	/** the column name for the ENTE_PUBLICO field */
	const ENTE_PUBLICO = 'tipodestino.ENTE_PUBLICO';

	/** the column name for the DONACION field */
	const DONACION = 'tipodestino.DONACION';

	/** the column name for the GRATUITA field */
	const GRATUITA = 'tipodestino.GRATUITA';

	/** the column name for the IMPORTACION field */
	const IMPORTACION = 'tipodestino.IMPORTACION';

	/** the column name for the EXPORTACION field */
	const EXPORTACION = 'tipodestino.EXPORTACION';

	/** the column name for the OTRO field */
	const OTRO = 'tipodestino.OTRO';

	/** the column name for the ID_FERIA field */
	const ID_FERIA = 'tipodestino.ID_FERIA';

	/** the column name for the ID_PAIS field */
	const ID_PAIS = 'tipodestino.ID_PAIS';

	/** the column name for the ID_ESTADO field */
	const ID_ESTADO = 'tipodestino.ID_ESTADO';

	/** the column name for the ID_LIBRERIA field */
	const ID_LIBRERIA = 'tipodestino.ID_LIBRERIA';

	/** the column name for the ID_MUNICIPIO field */
	const ID_MUNICIPIO = 'tipodestino.ID_MUNICIPIO';

	/**
	 * An identiy map to hold any loaded instances of Tipodestino objects.
	 * This must be public so that other peer classes can access this when hydrating from JOIN
	 * queries.
	 * @var        array Tipodestino[]
	 */
	public static $instances = array();


	// symfony behavior
	
	/**
	 * Indicates whether the current model includes I18N.
	 */
	const IS_I18N = false;

	/**
	 * holds an array of fieldnames
	 *
	 * first dimension keys are the type constants
	 * e.g. self::$fieldNames[self::TYPE_PHPNAME][0] = 'Id'
	 */
	private static $fieldNames = array (
		BasePeer::TYPE_PHPNAME => array ('Id', 'EntePublico', 'Donacion', 'Gratuita', 'Importacion', 'Exportacion', 'Otro', 'IdFeria', 'IdPais', 'IdEstado', 'IdLibreria', 'IdMunicipio', ),
		BasePeer::TYPE_STUDLYPHPNAME => array ('id', 'entePublico', 'donacion', 'gratuita', 'importacion', 'exportacion', 'otro', 'idFeria', 'idPais', 'idEstado', 'idLibreria', 'idMunicipio', ),
		BasePeer::TYPE_COLNAME => array (self::ID, self::ENTE_PUBLICO, self::DONACION, self::GRATUITA, self::IMPORTACION, self::EXPORTACION, self::OTRO, self::ID_FERIA, self::ID_PAIS, self::ID_ESTADO, self::ID_LIBRERIA, self::ID_MUNICIPIO, ),
		BasePeer::TYPE_RAW_COLNAME => array ('ID', 'ENTE_PUBLICO', 'DONACION', 'GRATUITA', 'IMPORTACION', 'EXPORTACION', 'OTRO', 'ID_FERIA', 'ID_PAIS', 'ID_ESTADO', 'ID_LIBRERIA', 'ID_MUNICIPIO', ),
		BasePeer::TYPE_FIELDNAME => array ('id', 'ente_publico', 'donacion', 'gratuita', 'importacion', 'exportacion', 'otro', 'id_feria', 'id_pais', 'id_estado', 'id_libreria', 'id_municipio', ),
		BasePeer::TYPE_NUM => array (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, )
	);

	/**
	 * holds an array of keys for quick access to the fieldnames array
	 *
	 * first dimension keys are the type constants
	 * e.g. self::$fieldNames[BasePeer::TYPE_PHPNAME]['Id'] = 0
	 */
	private static $fieldKeys = array (
		BasePeer::TYPE_PHPNAME => array ('Id' => 0, 'EntePublico' => 1, 'Donacion' => 2, 'Gratuita' => 3, 'Importacion' => 4, 'Exportacion' => 5, 'Otro' => 6, 'IdFeria' => 7, 'IdPais' => 8, 'IdEstado' => 9, 'IdLibreria' => 10, 'IdMunicipio' => 11, ),
		BasePeer::TYPE_STUDLYPHPNAME => array ('id' => 0, 'entePublico' => 1, 'donacion' => 2, 'gratuita' => 3, 'importacion' => 4, 'exportacion' => 5, 'otro' => 6, 'idFeria' => 7, 'idPais' => 8, 'idEstado' => 9, 'idLibreria' => 10, 'idMunicipio' => 11, ),
		BasePeer::TYPE_COLNAME => array (self::ID => 0, self::ENTE_PUBLICO => 1, self::DONACION => 2, self::GRATUITA => 3, self::IMPORTACION => 4, self::EXPORTACION => 5, self::OTRO => 6, self::ID_FERIA => 7, self::ID_PAIS => 8, self::ID_ESTADO => 9, self::ID_LIBRERIA => 10, self::ID_MUNICIPIO => 11, ),
		BasePeer::TYPE_RAW_COLNAME => array ('ID' => 0, 'ENTE_PUBLICO' => 1, 'DONACION' => 2, 'GRATUITA' => 3, 'IMPORTACION' => 4, 'EXPORTACION' => 5, 'OTRO' => 6, 'ID_FERIA' => 7, 'ID_PAIS' => 8, 'ID_ESTADO' => 9, 'ID_LIBRERIA' => 10, 'ID_MUNICIPIO' => 11, ),
		BasePeer::TYPE_FIELDNAME => array ('id' => 0, 'ente_publico' => 1, 'donacion' => 2, 'gratuita' => 3, 'importacion' => 4, 'exportacion' => 5, 'otro' => 6, 'id_feria' => 7, 'id_pais' => 8, 'id_estado' => 9, 'id_libreria' => 10, 'id_municipio' => 11, ),
		BasePeer::TYPE_NUM => array (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, )
	);

	/**
	 * Translates a fieldname to another type
	 *
	 * @param      string $name field name
	 * @param      string $fromType One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                         BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @param      string $toType   One of the class type constants
	 * @return     string translated name of the field.
	 * @throws     PropelException - if the specified name could not be found in the fieldname mappings.
	 */
	static public function translateFieldName($name, $fromType, $toType)
	{
		$toNames = self::getFieldNames($toType);
		$key = isset(self::$fieldKeys[$fromType][$name]) ? self::$fieldKeys[$fromType][$name] : null;
		if ($key === null) {
			throw new PropelException("'$name' could not be found in the field names of type '$fromType'. These are: " . print_r(self::$fieldKeys[$fromType], true));
		}
		return $toNames[$key];
	}

	/**
	 * Returns an array of field names.
	 *
	 * @param      string $type The type of fieldnames to return:
	 *                      One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                      BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     array A list of field names
	 */

	static public function getFieldNames($type = BasePeer::TYPE_PHPNAME)
	{
		if (!array_key_exists($type, self::$fieldNames)) {
			throw new PropelException('Method getFieldNames() expects the parameter $type to be one of the class constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME, BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. ' . $type . ' was given.');
		}
		return self::$fieldNames[$type];
	}

	/**
	 * Convenience method which changes table.column to alias.column.
	 *
	 * Using this method you can maintain SQL abstraction while using column aliases.
	 * <code>
	 *		$c->addAlias("alias1", TablePeer::TABLE_NAME);
	 *		$c->addJoin(TablePeer::alias("alias1", TablePeer::PRIMARY_KEY_COLUMN), TablePeer::PRIMARY_KEY_COLUMN);
	 * </code>
	 * @param      string $alias The alias for the current table.
	 * @param      string $column The column name for current table. (i.e. TipodestinoPeer::COLUMN_NAME).
	 * @return     string
	 */
	public static function alias($alias, $column)
	{
		return str_replace(TipodestinoPeer::TABLE_NAME.'.', $alias.'.', $column);
	}

	/**
	 * Add all the columns needed to create a new object.
	 *
	 * Note: any columns that were marked with lazyLoad="true" in the
	 * XML schema will not be added to the select list and only loaded
	 * on demand.
	 *
	 * @param      Criteria $criteria object containing the columns to add.
	 * @param      string   $alias    optional table alias
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function addSelectColumns(Criteria $criteria, $alias = null)
	{
		if (null === $alias) {
			$criteria->addSelectColumn(TipodestinoPeer::ID);
			$criteria->addSelectColumn(TipodestinoPeer::ENTE_PUBLICO);
			$criteria->addSelectColumn(TipodestinoPeer::DONACION);
			$criteria->addSelectColumn(TipodestinoPeer::GRATUITA);
			$criteria->addSelectColumn(TipodestinoPeer::IMPORTACION);
			$criteria->addSelectColumn(TipodestinoPeer::EXPORTACION);
			$criteria->addSelectColumn(TipodestinoPeer::OTRO);
			$criteria->addSelectColumn(TipodestinoPeer::ID_FERIA);
			$criteria->addSelectColumn(TipodestinoPeer::ID_PAIS);
			$criteria->addSelectColumn(TipodestinoPeer::ID_ESTADO);
			$criteria->addSelectColumn(TipodestinoPeer::ID_LIBRERIA);
			$criteria->addSelectColumn(TipodestinoPeer::ID_MUNICIPIO);
		} else {
			$criteria->addSelectColumn($alias . '.ID');
			$criteria->addSelectColumn($alias . '.ENTE_PUBLICO');
			$criteria->addSelectColumn($alias . '.DONACION');
			$criteria->addSelectColumn($alias . '.GRATUITA');
			$criteria->addSelectColumn($alias . '.IMPORTACION');
			$criteria->addSelectColumn($alias . '.EXPORTACION');
			$criteria->addSelectColumn($alias . '.OTRO');
			$criteria->addSelectColumn($alias . '.ID_FERIA');
			$criteria->addSelectColumn($alias . '.ID_PAIS');
			$criteria->addSelectColumn($alias . '.ID_ESTADO');
			$criteria->addSelectColumn($alias . '.ID_LIBRERIA');
			$criteria->addSelectColumn($alias . '.ID_MUNICIPIO');
		}
	}

	/**
	 * Returns the number of rows matching criteria.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @return     int Number of matching rows.
	 */
	public static function doCount(Criteria $criteria, $distinct = false, PropelPDO $con = null)
	{
		// we may modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(TipodestinoPeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			TipodestinoPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count
		$criteria->setDbName(self::DATABASE_NAME); // Set the correct dbName

		if ($con === null) {
			$con = Propel::getConnection(TipodestinoPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}
		// symfony_behaviors behavior
		foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
		{
		  call_user_func($sf_hook, 'BaseTipodestinoPeer', $criteria, $con);
		}

		// BasePeer returns a PDOStatement
		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}
	/**
	 * Method to select one object from the DB.
	 *
	 * @param      Criteria $criteria object used to create the SELECT statement.
	 * @param      PropelPDO $con
	 * @return     Tipodestino
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectOne(Criteria $criteria, PropelPDO $con = null)
	{
		$critcopy = clone $criteria;
		$critcopy->setLimit(1);
		$objects = TipodestinoPeer::doSelect($critcopy, $con);
		if ($objects) {
			return $objects[0];
		}
		return null;
	}
	/**
	 * Method to do selects.
	 *
	 * @param      Criteria $criteria The Criteria object used to build the SELECT statement.
	 * @param      PropelPDO $con
	 * @return     array Array of selected Objects
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelect(Criteria $criteria, PropelPDO $con = null)
	{
		return TipodestinoPeer::populateObjects(TipodestinoPeer::doSelectStmt($criteria, $con));
	}
	/**
	 * Prepares the Criteria object and uses the parent doSelect() method to execute a PDOStatement.
	 *
	 * Use this method directly if you want to work with an executed statement durirectly (for example
	 * to perform your own object hydration).
	 *
	 * @param      Criteria $criteria The Criteria object used to build the SELECT statement.
	 * @param      PropelPDO $con The connection to use
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 * @return     PDOStatement The executed PDOStatement object.
	 * @see        BasePeer::doSelect()
	 */
	public static function doSelectStmt(Criteria $criteria, PropelPDO $con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(TipodestinoPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		if (!$criteria->hasSelectClause()) {
			$criteria = clone $criteria;
			TipodestinoPeer::addSelectColumns($criteria);
		}

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);
		// symfony_behaviors behavior
		foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
		{
		  call_user_func($sf_hook, 'BaseTipodestinoPeer', $criteria, $con);
		}


		// BasePeer returns a PDOStatement
		return BasePeer::doSelect($criteria, $con);
	}
	/**
	 * Adds an object to the instance pool.
	 *
	 * Propel keeps cached copies of objects in an instance pool when they are retrieved
	 * from the database.  In some cases -- especially when you override doSelect*()
	 * methods in your stub classes -- you may need to explicitly add objects
	 * to the cache in order to ensure that the same objects are always returned by doSelect*()
	 * and retrieveByPK*() calls.
	 *
	 * @param      Tipodestino $value A Tipodestino object.
	 * @param      string $key (optional) key to use for instance map (for performance boost if key was already calculated externally).
	 */
	public static function addInstanceToPool(Tipodestino $obj, $key = null)
	{
		if (Propel::isInstancePoolingEnabled()) {
			if ($key === null) {
				$key = (string) $obj->getId();
			} // if key === null
			self::$instances[$key] = $obj;
		}
	}

	/**
	 * Removes an object from the instance pool.
	 *
	 * Propel keeps cached copies of objects in an instance pool when they are retrieved
	 * from the database.  In some cases -- especially when you override doDelete
	 * methods in your stub classes -- you may need to explicitly remove objects
	 * from the cache in order to prevent returning objects that no longer exist.
	 *
	 * @param      mixed $value A Tipodestino object or a primary key value.
	 */
	public static function removeInstanceFromPool($value)
	{
		if (Propel::isInstancePoolingEnabled() && $value !== null) {
			if (is_object($value) && $value instanceof Tipodestino) {
				$key = (string) $value->getId();
			} elseif (is_scalar($value)) {
				// assume we've been passed a primary key
				$key = (string) $value;
			} else {
				$e = new PropelException("Invalid value passed to removeInstanceFromPool().  Expected primary key or Tipodestino object; got " . (is_object($value) ? get_class($value) . ' object.' : var_export($value,true)));
				throw $e;
			}

			unset(self::$instances[$key]);
		}
	} // removeInstanceFromPool()

	/**
	 * Retrieves a string version of the primary key from the DB resultset row that can be used to uniquely identify a row in this table.
	 *
	 * For tables with a single-column primary key, that simple pkey value will be returned.  For tables with
	 * a multi-column primary key, a serialize()d version of the primary key will be returned.
	 *
	 * @param      string $key The key (@see getPrimaryKeyHash()) for this instance.
	 * @return     Tipodestino Found object or NULL if 1) no instance exists for specified key or 2) instance pooling has been disabled.
	 * @see        getPrimaryKeyHash()
	 */
	public static function getInstanceFromPool($key)
	{
		if (Propel::isInstancePoolingEnabled()) {
			if (isset(self::$instances[$key])) {
				return self::$instances[$key];
			}
		}
		return null; // just to be explicit
	}
	
	/**
	 * Clear the instance pool.
	 *
	 * @return     void
	 */
	public static function clearInstancePool()
	{
		self::$instances = array();
	}
	
	/**
	 * Method to invalidate the instance pool of all tables related to tipodestino
	 * by a foreign key with ON DELETE CASCADE
	 */
	public static function clearRelatedInstancePool()
	{
	}

	/**
	 * Retrieves a string version of the primary key from the DB resultset row that can be used to uniquely identify a row in this table.
	 *
	 * For tables with a single-column primary key, that simple pkey value will be returned.  For tables with
	 * a multi-column primary key, a serialize()d version of the primary key will be returned.
	 *
	 * @param      array $row PropelPDO resultset row.
	 * @param      int $startcol The 0-based offset for reading from the resultset row.
	 * @return     string A string version of PK or NULL if the components of primary key in result array are all null.
	 */
	public static function getPrimaryKeyHashFromRow($row, $startcol = 0)
	{
		// If the PK cannot be derived from the row, return NULL.
		if ($row[$startcol] === null) {
			return null;
		}
		return (string) $row[$startcol];
	}

	/**
	 * Retrieves the primary key from the DB resultset row 
	 * For tables with a single-column primary key, that simple pkey value will be returned.  For tables with
	 * a multi-column primary key, an array of the primary key columns will be returned.
	 *
	 * @param      array $row PropelPDO resultset row.
	 * @param      int $startcol The 0-based offset for reading from the resultset row.
	 * @return     mixed The primary key of the row
	 */
	public static function getPrimaryKeyFromRow($row, $startcol = 0)
	{
		return (string) $row[$startcol];
	}
	
	/**
	 * The returned array will contain objects of the default type or
	 * objects that inherit from the default.
	 *
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function populateObjects(PDOStatement $stmt)
	{
		$results = array();
	
		// set the class once to avoid overhead in the loop
		$cls = TipodestinoPeer::getOMClass(false);
		// populate the object(s)
		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key = TipodestinoPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj = TipodestinoPeer::getInstanceFromPool($key))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://www.propelorm.org/ticket/509
				// $obj->hydrate($row, 0, true); // rehydrate
				$results[] = $obj;
			} else {
				$obj = new $cls();
				$obj->hydrate($row);
				$results[] = $obj;
				TipodestinoPeer::addInstanceToPool($obj, $key);
			} // if key exists
		}
		$stmt->closeCursor();
		return $results;
	}
	/**
	 * Populates an object of the default type or an object that inherit from the default.
	 *
	 * @param      array $row PropelPDO resultset row.
	 * @param      int $startcol The 0-based offset for reading from the resultset row.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 * @return     array (Tipodestino object, last column rank)
	 */
	public static function populateObject($row, $startcol = 0)
	{
		$key = TipodestinoPeer::getPrimaryKeyHashFromRow($row, $startcol);
		if (null !== ($obj = TipodestinoPeer::getInstanceFromPool($key))) {
			// We no longer rehydrate the object, since this can cause data loss.
			// See http://www.propelorm.org/ticket/509
			// $obj->hydrate($row, $startcol, true); // rehydrate
			$col = $startcol + TipodestinoPeer::NUM_COLUMNS;
		} else {
			$cls = TipodestinoPeer::OM_CLASS;
			$obj = new $cls();
			$col = $obj->hydrate($row, $startcol);
			TipodestinoPeer::addInstanceToPool($obj, $key);
		}
		return array($obj, $col);
	}

	/**
	 * Returns the number of rows matching criteria, joining the related Feria table
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinFeria(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(TipodestinoPeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			TipodestinoPeer::addSelectColumns($criteria);
		}
		
		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count
		
		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(TipodestinoPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria->addJoin(TipodestinoPeer::ID_FERIA, FeriaPeer::ID, $join_behavior);

		// symfony_behaviors behavior
		foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
		{
		  call_user_func($sf_hook, 'BaseTipodestinoPeer', $criteria, $con);
		}

		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Returns the number of rows matching criteria, joining the related Pais table
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinPais(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(TipodestinoPeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			TipodestinoPeer::addSelectColumns($criteria);
		}
		
		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count
		
		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(TipodestinoPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria->addJoin(TipodestinoPeer::ID_PAIS, PaisPeer::ID, $join_behavior);

		// symfony_behaviors behavior
		foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
		{
		  call_user_func($sf_hook, 'BaseTipodestinoPeer', $criteria, $con);
		}

		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Returns the number of rows matching criteria, joining the related Estado table
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinEstado(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(TipodestinoPeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			TipodestinoPeer::addSelectColumns($criteria);
		}
		
		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count
		
		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(TipodestinoPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria->addJoin(TipodestinoPeer::ID_ESTADO, EstadoPeer::ID, $join_behavior);

		// symfony_behaviors behavior
		foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
		{
		  call_user_func($sf_hook, 'BaseTipodestinoPeer', $criteria, $con);
		}

		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Returns the number of rows matching criteria, joining the related Libreria table
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinLibreria(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(TipodestinoPeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			TipodestinoPeer::addSelectColumns($criteria);
		}
		
		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count
		
		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(TipodestinoPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria->addJoin(TipodestinoPeer::ID_LIBRERIA, LibreriaPeer::ID, $join_behavior);

		// symfony_behaviors behavior
		foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
		{
		  call_user_func($sf_hook, 'BaseTipodestinoPeer', $criteria, $con);
		}

		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Returns the number of rows matching criteria, joining the related Municipio table
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinMunicipio(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(TipodestinoPeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			TipodestinoPeer::addSelectColumns($criteria);
		}
		
		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count
		
		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(TipodestinoPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria->addJoin(TipodestinoPeer::ID_MUNICIPIO, MunicipioPeer::ID, $join_behavior);

		// symfony_behaviors behavior
		foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
		{
		  call_user_func($sf_hook, 'BaseTipodestinoPeer', $criteria, $con);
		}

		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Selects a collection of Tipodestino objects pre-filled with their Feria objects.
	 * @param      Criteria  $criteria
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of Tipodestino objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinFeria(Criteria $criteria, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		$criteria = clone $criteria;

		// Set the correct dbName if it has not been overridden
		if ($criteria->getDbName() == Propel::getDefaultDB()) {
			$criteria->setDbName(self::DATABASE_NAME);
		}

		TipodestinoPeer::addSelectColumns($criteria);
		$startcol = (TipodestinoPeer::NUM_COLUMNS - TipodestinoPeer::NUM_LAZY_LOAD_COLUMNS);
		FeriaPeer::addSelectColumns($criteria);

		$criteria->addJoin(TipodestinoPeer::ID_FERIA, FeriaPeer::ID, $join_behavior);

		// symfony_behaviors behavior
		foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
		{
		  call_user_func($sf_hook, 'BaseTipodestinoPeer', $criteria, $con);
		}

		$stmt = BasePeer::doSelect($criteria, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = TipodestinoPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = TipodestinoPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://www.propelorm.org/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {

				$cls = TipodestinoPeer::getOMClass(false);

				$obj1 = new $cls();
				$obj1->hydrate($row);
				TipodestinoPeer::addInstanceToPool($obj1, $key1);
			} // if $obj1 already loaded

			$key2 = FeriaPeer::getPrimaryKeyHashFromRow($row, $startcol);
			if ($key2 !== null) {
				$obj2 = FeriaPeer::getInstanceFromPool($key2);
				if (!$obj2) {

					$cls = FeriaPeer::getOMClass(false);

					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol);
					FeriaPeer::addInstanceToPool($obj2, $key2);
				} // if obj2 already loaded

				// Add the $obj1 (Tipodestino) to $obj2 (Feria)
				$obj2->addTipodestino($obj1);

			} // if joined row was not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Selects a collection of Tipodestino objects pre-filled with their Pais objects.
	 * @param      Criteria  $criteria
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of Tipodestino objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinPais(Criteria $criteria, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		$criteria = clone $criteria;

		// Set the correct dbName if it has not been overridden
		if ($criteria->getDbName() == Propel::getDefaultDB()) {
			$criteria->setDbName(self::DATABASE_NAME);
		}

		TipodestinoPeer::addSelectColumns($criteria);
		$startcol = (TipodestinoPeer::NUM_COLUMNS - TipodestinoPeer::NUM_LAZY_LOAD_COLUMNS);
		PaisPeer::addSelectColumns($criteria);

		$criteria->addJoin(TipodestinoPeer::ID_PAIS, PaisPeer::ID, $join_behavior);

		// symfony_behaviors behavior
		foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
		{
		  call_user_func($sf_hook, 'BaseTipodestinoPeer', $criteria, $con);
		}

		$stmt = BasePeer::doSelect($criteria, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = TipodestinoPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = TipodestinoPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://www.propelorm.org/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {

				$cls = TipodestinoPeer::getOMClass(false);

				$obj1 = new $cls();
				$obj1->hydrate($row);
				TipodestinoPeer::addInstanceToPool($obj1, $key1);
			} // if $obj1 already loaded

			$key2 = PaisPeer::getPrimaryKeyHashFromRow($row, $startcol);
			if ($key2 !== null) {
				$obj2 = PaisPeer::getInstanceFromPool($key2);
				if (!$obj2) {

					$cls = PaisPeer::getOMClass(false);

					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol);
					PaisPeer::addInstanceToPool($obj2, $key2);
				} // if obj2 already loaded

				// Add the $obj1 (Tipodestino) to $obj2 (Pais)
				$obj2->addTipodestino($obj1);

			} // if joined row was not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Selects a collection of Tipodestino objects pre-filled with their Estado objects.
	 * @param      Criteria  $criteria
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of Tipodestino objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinEstado(Criteria $criteria, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		$criteria = clone $criteria;

		// Set the correct dbName if it has not been overridden
		if ($criteria->getDbName() == Propel::getDefaultDB()) {
			$criteria->setDbName(self::DATABASE_NAME);
		}

		TipodestinoPeer::addSelectColumns($criteria);
		$startcol = (TipodestinoPeer::NUM_COLUMNS - TipodestinoPeer::NUM_LAZY_LOAD_COLUMNS);
		EstadoPeer::addSelectColumns($criteria);

		$criteria->addJoin(TipodestinoPeer::ID_ESTADO, EstadoPeer::ID, $join_behavior);

		// symfony_behaviors behavior
		foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
		{
		  call_user_func($sf_hook, 'BaseTipodestinoPeer', $criteria, $con);
		}

		$stmt = BasePeer::doSelect($criteria, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = TipodestinoPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = TipodestinoPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://www.propelorm.org/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {

				$cls = TipodestinoPeer::getOMClass(false);

				$obj1 = new $cls();
				$obj1->hydrate($row);
				TipodestinoPeer::addInstanceToPool($obj1, $key1);
			} // if $obj1 already loaded

			$key2 = EstadoPeer::getPrimaryKeyHashFromRow($row, $startcol);
			if ($key2 !== null) {
				$obj2 = EstadoPeer::getInstanceFromPool($key2);
				if (!$obj2) {

					$cls = EstadoPeer::getOMClass(false);

					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol);
					EstadoPeer::addInstanceToPool($obj2, $key2);
				} // if obj2 already loaded

				// Add the $obj1 (Tipodestino) to $obj2 (Estado)
				$obj2->addTipodestino($obj1);

			} // if joined row was not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Selects a collection of Tipodestino objects pre-filled with their Libreria objects.
	 * @param      Criteria  $criteria
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of Tipodestino objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinLibreria(Criteria $criteria, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		$criteria = clone $criteria;

		// Set the correct dbName if it has not been overridden
		if ($criteria->getDbName() == Propel::getDefaultDB()) {
			$criteria->setDbName(self::DATABASE_NAME);
		}

		TipodestinoPeer::addSelectColumns($criteria);
		$startcol = (TipodestinoPeer::NUM_COLUMNS - TipodestinoPeer::NUM_LAZY_LOAD_COLUMNS);
		LibreriaPeer::addSelectColumns($criteria);

		$criteria->addJoin(TipodestinoPeer::ID_LIBRERIA, LibreriaPeer::ID, $join_behavior);

		// symfony_behaviors behavior
		foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
		{
		  call_user_func($sf_hook, 'BaseTipodestinoPeer', $criteria, $con);
		}

		$stmt = BasePeer::doSelect($criteria, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = TipodestinoPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = TipodestinoPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://www.propelorm.org/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {

				$cls = TipodestinoPeer::getOMClass(false);

				$obj1 = new $cls();
				$obj1->hydrate($row);
				TipodestinoPeer::addInstanceToPool($obj1, $key1);
			} // if $obj1 already loaded

			$key2 = LibreriaPeer::getPrimaryKeyHashFromRow($row, $startcol);
			if ($key2 !== null) {
				$obj2 = LibreriaPeer::getInstanceFromPool($key2);
				if (!$obj2) {

					$cls = LibreriaPeer::getOMClass(false);

					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol);
					LibreriaPeer::addInstanceToPool($obj2, $key2);
				} // if obj2 already loaded

				// Add the $obj1 (Tipodestino) to $obj2 (Libreria)
				$obj2->addTipodestino($obj1);

			} // if joined row was not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Selects a collection of Tipodestino objects pre-filled with their Municipio objects.
	 * @param      Criteria  $criteria
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of Tipodestino objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinMunicipio(Criteria $criteria, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		$criteria = clone $criteria;

		// Set the correct dbName if it has not been overridden
		if ($criteria->getDbName() == Propel::getDefaultDB()) {
			$criteria->setDbName(self::DATABASE_NAME);
		}

		TipodestinoPeer::addSelectColumns($criteria);
		$startcol = (TipodestinoPeer::NUM_COLUMNS - TipodestinoPeer::NUM_LAZY_LOAD_COLUMNS);
		MunicipioPeer::addSelectColumns($criteria);

		$criteria->addJoin(TipodestinoPeer::ID_MUNICIPIO, MunicipioPeer::ID, $join_behavior);

		// symfony_behaviors behavior
		foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
		{
		  call_user_func($sf_hook, 'BaseTipodestinoPeer', $criteria, $con);
		}

		$stmt = BasePeer::doSelect($criteria, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = TipodestinoPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = TipodestinoPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://www.propelorm.org/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {

				$cls = TipodestinoPeer::getOMClass(false);

				$obj1 = new $cls();
				$obj1->hydrate($row);
				TipodestinoPeer::addInstanceToPool($obj1, $key1);
			} // if $obj1 already loaded

			$key2 = MunicipioPeer::getPrimaryKeyHashFromRow($row, $startcol);
			if ($key2 !== null) {
				$obj2 = MunicipioPeer::getInstanceFromPool($key2);
				if (!$obj2) {

					$cls = MunicipioPeer::getOMClass(false);

					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol);
					MunicipioPeer::addInstanceToPool($obj2, $key2);
				} // if obj2 already loaded

				// Add the $obj1 (Tipodestino) to $obj2 (Municipio)
				$obj2->addTipodestino($obj1);

			} // if joined row was not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Returns the number of rows matching criteria, joining all related tables
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinAll(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(TipodestinoPeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			TipodestinoPeer::addSelectColumns($criteria);
		}
		
		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count
		
		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(TipodestinoPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria->addJoin(TipodestinoPeer::ID_FERIA, FeriaPeer::ID, $join_behavior);

		$criteria->addJoin(TipodestinoPeer::ID_PAIS, PaisPeer::ID, $join_behavior);

		$criteria->addJoin(TipodestinoPeer::ID_ESTADO, EstadoPeer::ID, $join_behavior);

		$criteria->addJoin(TipodestinoPeer::ID_LIBRERIA, LibreriaPeer::ID, $join_behavior);

		$criteria->addJoin(TipodestinoPeer::ID_MUNICIPIO, MunicipioPeer::ID, $join_behavior);

		// symfony_behaviors behavior
		foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
		{
		  call_user_func($sf_hook, 'BaseTipodestinoPeer', $criteria, $con);
		}

		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}

	/**
	 * Selects a collection of Tipodestino objects pre-filled with all related objects.
	 *
	 * @param      Criteria  $criteria
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of Tipodestino objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinAll(Criteria $criteria, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		$criteria = clone $criteria;

		// Set the correct dbName if it has not been overridden
		if ($criteria->getDbName() == Propel::getDefaultDB()) {
			$criteria->setDbName(self::DATABASE_NAME);
		}

		TipodestinoPeer::addSelectColumns($criteria);
		$startcol2 = (TipodestinoPeer::NUM_COLUMNS - TipodestinoPeer::NUM_LAZY_LOAD_COLUMNS);

		FeriaPeer::addSelectColumns($criteria);
		$startcol3 = $startcol2 + (FeriaPeer::NUM_COLUMNS - FeriaPeer::NUM_LAZY_LOAD_COLUMNS);

		PaisPeer::addSelectColumns($criteria);
		$startcol4 = $startcol3 + (PaisPeer::NUM_COLUMNS - PaisPeer::NUM_LAZY_LOAD_COLUMNS);

		EstadoPeer::addSelectColumns($criteria);
		$startcol5 = $startcol4 + (EstadoPeer::NUM_COLUMNS - EstadoPeer::NUM_LAZY_LOAD_COLUMNS);

		LibreriaPeer::addSelectColumns($criteria);
		$startcol6 = $startcol5 + (LibreriaPeer::NUM_COLUMNS - LibreriaPeer::NUM_LAZY_LOAD_COLUMNS);

		MunicipioPeer::addSelectColumns($criteria);
		$startcol7 = $startcol6 + (MunicipioPeer::NUM_COLUMNS - MunicipioPeer::NUM_LAZY_LOAD_COLUMNS);

		$criteria->addJoin(TipodestinoPeer::ID_FERIA, FeriaPeer::ID, $join_behavior);

		$criteria->addJoin(TipodestinoPeer::ID_PAIS, PaisPeer::ID, $join_behavior);

		$criteria->addJoin(TipodestinoPeer::ID_ESTADO, EstadoPeer::ID, $join_behavior);

		$criteria->addJoin(TipodestinoPeer::ID_LIBRERIA, LibreriaPeer::ID, $join_behavior);

		$criteria->addJoin(TipodestinoPeer::ID_MUNICIPIO, MunicipioPeer::ID, $join_behavior);

		// symfony_behaviors behavior
		foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
		{
		  call_user_func($sf_hook, 'BaseTipodestinoPeer', $criteria, $con);
		}

		$stmt = BasePeer::doSelect($criteria, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = TipodestinoPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = TipodestinoPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://www.propelorm.org/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {
				$cls = TipodestinoPeer::getOMClass(false);

				$obj1 = new $cls();
				$obj1->hydrate($row);
				TipodestinoPeer::addInstanceToPool($obj1, $key1);
			} // if obj1 already loaded

			// Add objects for joined Feria rows

			$key2 = FeriaPeer::getPrimaryKeyHashFromRow($row, $startcol2);
			if ($key2 !== null) {
				$obj2 = FeriaPeer::getInstanceFromPool($key2);
				if (!$obj2) {

					$cls = FeriaPeer::getOMClass(false);

					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol2);
					FeriaPeer::addInstanceToPool($obj2, $key2);
				} // if obj2 loaded

				// Add the $obj1 (Tipodestino) to the collection in $obj2 (Feria)
				$obj2->addTipodestino($obj1);
			} // if joined row not null

			// Add objects for joined Pais rows

			$key3 = PaisPeer::getPrimaryKeyHashFromRow($row, $startcol3);
			if ($key3 !== null) {
				$obj3 = PaisPeer::getInstanceFromPool($key3);
				if (!$obj3) {

					$cls = PaisPeer::getOMClass(false);

					$obj3 = new $cls();
					$obj3->hydrate($row, $startcol3);
					PaisPeer::addInstanceToPool($obj3, $key3);
				} // if obj3 loaded

				// Add the $obj1 (Tipodestino) to the collection in $obj3 (Pais)
				$obj3->addTipodestino($obj1);
			} // if joined row not null

			// Add objects for joined Estado rows

			$key4 = EstadoPeer::getPrimaryKeyHashFromRow($row, $startcol4);
			if ($key4 !== null) {
				$obj4 = EstadoPeer::getInstanceFromPool($key4);
				if (!$obj4) {

					$cls = EstadoPeer::getOMClass(false);

					$obj4 = new $cls();
					$obj4->hydrate($row, $startcol4);
					EstadoPeer::addInstanceToPool($obj4, $key4);
				} // if obj4 loaded

				// Add the $obj1 (Tipodestino) to the collection in $obj4 (Estado)
				$obj4->addTipodestino($obj1);
			} // if joined row not null

			// Add objects for joined Libreria rows

			$key5 = LibreriaPeer::getPrimaryKeyHashFromRow($row, $startcol5);
			if ($key5 !== null) {
				$obj5 = LibreriaPeer::getInstanceFromPool($key5);
				if (!$obj5) {

					$cls = LibreriaPeer::getOMClass(false);

					$obj5 = new $cls();
					$obj5->hydrate($row, $startcol5);
					LibreriaPeer::addInstanceToPool($obj5, $key5);
				} // if obj5 loaded

				// Add the $obj1 (Tipodestino) to the collection in $obj5 (Libreria)
				$obj5->addTipodestino($obj1);
			} // if joined row not null

			// Add objects for joined Municipio rows

			$key6 = MunicipioPeer::getPrimaryKeyHashFromRow($row, $startcol6);
			if ($key6 !== null) {
				$obj6 = MunicipioPeer::getInstanceFromPool($key6);
				if (!$obj6) {

					$cls = MunicipioPeer::getOMClass(false);

					$obj6 = new $cls();
					$obj6->hydrate($row, $startcol6);
					MunicipioPeer::addInstanceToPool($obj6, $key6);
				} // if obj6 loaded

				// Add the $obj1 (Tipodestino) to the collection in $obj6 (Municipio)
				$obj6->addTipodestino($obj1);
			} // if joined row not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Returns the number of rows matching criteria, joining the related Feria table
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinAllExceptFeria(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(TipodestinoPeer::TABLE_NAME);
		
		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			TipodestinoPeer::addSelectColumns($criteria);
		}
		
		$criteria->clearOrderByColumns(); // ORDER BY should not affect count
		
		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(TipodestinoPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}
	
		$criteria->addJoin(TipodestinoPeer::ID_PAIS, PaisPeer::ID, $join_behavior);

		$criteria->addJoin(TipodestinoPeer::ID_ESTADO, EstadoPeer::ID, $join_behavior);

		$criteria->addJoin(TipodestinoPeer::ID_LIBRERIA, LibreriaPeer::ID, $join_behavior);

		$criteria->addJoin(TipodestinoPeer::ID_MUNICIPIO, MunicipioPeer::ID, $join_behavior);

		// symfony_behaviors behavior
		foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
		{
		  call_user_func($sf_hook, 'BaseTipodestinoPeer', $criteria, $con);
		}

		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Returns the number of rows matching criteria, joining the related Pais table
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinAllExceptPais(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(TipodestinoPeer::TABLE_NAME);
		
		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			TipodestinoPeer::addSelectColumns($criteria);
		}
		
		$criteria->clearOrderByColumns(); // ORDER BY should not affect count
		
		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(TipodestinoPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}
	
		$criteria->addJoin(TipodestinoPeer::ID_FERIA, FeriaPeer::ID, $join_behavior);

		$criteria->addJoin(TipodestinoPeer::ID_ESTADO, EstadoPeer::ID, $join_behavior);

		$criteria->addJoin(TipodestinoPeer::ID_LIBRERIA, LibreriaPeer::ID, $join_behavior);

		$criteria->addJoin(TipodestinoPeer::ID_MUNICIPIO, MunicipioPeer::ID, $join_behavior);

		// symfony_behaviors behavior
		foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
		{
		  call_user_func($sf_hook, 'BaseTipodestinoPeer', $criteria, $con);
		}

		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Returns the number of rows matching criteria, joining the related Estado table
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinAllExceptEstado(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(TipodestinoPeer::TABLE_NAME);
		
		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			TipodestinoPeer::addSelectColumns($criteria);
		}
		
		$criteria->clearOrderByColumns(); // ORDER BY should not affect count
		
		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(TipodestinoPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}
	
		$criteria->addJoin(TipodestinoPeer::ID_FERIA, FeriaPeer::ID, $join_behavior);

		$criteria->addJoin(TipodestinoPeer::ID_PAIS, PaisPeer::ID, $join_behavior);

		$criteria->addJoin(TipodestinoPeer::ID_LIBRERIA, LibreriaPeer::ID, $join_behavior);

		$criteria->addJoin(TipodestinoPeer::ID_MUNICIPIO, MunicipioPeer::ID, $join_behavior);

		// symfony_behaviors behavior
		foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
		{
		  call_user_func($sf_hook, 'BaseTipodestinoPeer', $criteria, $con);
		}

		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Returns the number of rows matching criteria, joining the related Libreria table
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinAllExceptLibreria(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(TipodestinoPeer::TABLE_NAME);
		
		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			TipodestinoPeer::addSelectColumns($criteria);
		}
		
		$criteria->clearOrderByColumns(); // ORDER BY should not affect count
		
		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(TipodestinoPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}
	
		$criteria->addJoin(TipodestinoPeer::ID_FERIA, FeriaPeer::ID, $join_behavior);

		$criteria->addJoin(TipodestinoPeer::ID_PAIS, PaisPeer::ID, $join_behavior);

		$criteria->addJoin(TipodestinoPeer::ID_ESTADO, EstadoPeer::ID, $join_behavior);

		$criteria->addJoin(TipodestinoPeer::ID_MUNICIPIO, MunicipioPeer::ID, $join_behavior);

		// symfony_behaviors behavior
		foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
		{
		  call_user_func($sf_hook, 'BaseTipodestinoPeer', $criteria, $con);
		}

		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Returns the number of rows matching criteria, joining the related Municipio table
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinAllExceptMunicipio(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(TipodestinoPeer::TABLE_NAME);
		
		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			TipodestinoPeer::addSelectColumns($criteria);
		}
		
		$criteria->clearOrderByColumns(); // ORDER BY should not affect count
		
		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(TipodestinoPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}
	
		$criteria->addJoin(TipodestinoPeer::ID_FERIA, FeriaPeer::ID, $join_behavior);

		$criteria->addJoin(TipodestinoPeer::ID_PAIS, PaisPeer::ID, $join_behavior);

		$criteria->addJoin(TipodestinoPeer::ID_ESTADO, EstadoPeer::ID, $join_behavior);

		$criteria->addJoin(TipodestinoPeer::ID_LIBRERIA, LibreriaPeer::ID, $join_behavior);

		// symfony_behaviors behavior
		foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
		{
		  call_user_func($sf_hook, 'BaseTipodestinoPeer', $criteria, $con);
		}

		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Selects a collection of Tipodestino objects pre-filled with all related objects except Feria.
	 *
	 * @param      Criteria  $criteria
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of Tipodestino objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinAllExceptFeria(Criteria $criteria, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		$criteria = clone $criteria;

		// Set the correct dbName if it has not been overridden
		// $criteria->getDbName() will return the same object if not set to another value
		// so == check is okay and faster
		if ($criteria->getDbName() == Propel::getDefaultDB()) {
			$criteria->setDbName(self::DATABASE_NAME);
		}

		TipodestinoPeer::addSelectColumns($criteria);
		$startcol2 = (TipodestinoPeer::NUM_COLUMNS - TipodestinoPeer::NUM_LAZY_LOAD_COLUMNS);

		PaisPeer::addSelectColumns($criteria);
		$startcol3 = $startcol2 + (PaisPeer::NUM_COLUMNS - PaisPeer::NUM_LAZY_LOAD_COLUMNS);

		EstadoPeer::addSelectColumns($criteria);
		$startcol4 = $startcol3 + (EstadoPeer::NUM_COLUMNS - EstadoPeer::NUM_LAZY_LOAD_COLUMNS);

		LibreriaPeer::addSelectColumns($criteria);
		$startcol5 = $startcol4 + (LibreriaPeer::NUM_COLUMNS - LibreriaPeer::NUM_LAZY_LOAD_COLUMNS);

		MunicipioPeer::addSelectColumns($criteria);
		$startcol6 = $startcol5 + (MunicipioPeer::NUM_COLUMNS - MunicipioPeer::NUM_LAZY_LOAD_COLUMNS);

		$criteria->addJoin(TipodestinoPeer::ID_PAIS, PaisPeer::ID, $join_behavior);

		$criteria->addJoin(TipodestinoPeer::ID_ESTADO, EstadoPeer::ID, $join_behavior);

		$criteria->addJoin(TipodestinoPeer::ID_LIBRERIA, LibreriaPeer::ID, $join_behavior);

		$criteria->addJoin(TipodestinoPeer::ID_MUNICIPIO, MunicipioPeer::ID, $join_behavior);

		// symfony_behaviors behavior
		foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
		{
		  call_user_func($sf_hook, 'BaseTipodestinoPeer', $criteria, $con);
		}


		$stmt = BasePeer::doSelect($criteria, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = TipodestinoPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = TipodestinoPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://www.propelorm.org/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {
				$cls = TipodestinoPeer::getOMClass(false);

				$obj1 = new $cls();
				$obj1->hydrate($row);
				TipodestinoPeer::addInstanceToPool($obj1, $key1);
			} // if obj1 already loaded

				// Add objects for joined Pais rows

				$key2 = PaisPeer::getPrimaryKeyHashFromRow($row, $startcol2);
				if ($key2 !== null) {
					$obj2 = PaisPeer::getInstanceFromPool($key2);
					if (!$obj2) {
	
						$cls = PaisPeer::getOMClass(false);

					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol2);
					PaisPeer::addInstanceToPool($obj2, $key2);
				} // if $obj2 already loaded

				// Add the $obj1 (Tipodestino) to the collection in $obj2 (Pais)
				$obj2->addTipodestino($obj1);

			} // if joined row is not null

				// Add objects for joined Estado rows

				$key3 = EstadoPeer::getPrimaryKeyHashFromRow($row, $startcol3);
				if ($key3 !== null) {
					$obj3 = EstadoPeer::getInstanceFromPool($key3);
					if (!$obj3) {
	
						$cls = EstadoPeer::getOMClass(false);

					$obj3 = new $cls();
					$obj3->hydrate($row, $startcol3);
					EstadoPeer::addInstanceToPool($obj3, $key3);
				} // if $obj3 already loaded

				// Add the $obj1 (Tipodestino) to the collection in $obj3 (Estado)
				$obj3->addTipodestino($obj1);

			} // if joined row is not null

				// Add objects for joined Libreria rows

				$key4 = LibreriaPeer::getPrimaryKeyHashFromRow($row, $startcol4);
				if ($key4 !== null) {
					$obj4 = LibreriaPeer::getInstanceFromPool($key4);
					if (!$obj4) {
	
						$cls = LibreriaPeer::getOMClass(false);

					$obj4 = new $cls();
					$obj4->hydrate($row, $startcol4);
					LibreriaPeer::addInstanceToPool($obj4, $key4);
				} // if $obj4 already loaded

				// Add the $obj1 (Tipodestino) to the collection in $obj4 (Libreria)
				$obj4->addTipodestino($obj1);

			} // if joined row is not null

				// Add objects for joined Municipio rows

				$key5 = MunicipioPeer::getPrimaryKeyHashFromRow($row, $startcol5);
				if ($key5 !== null) {
					$obj5 = MunicipioPeer::getInstanceFromPool($key5);
					if (!$obj5) {
	
						$cls = MunicipioPeer::getOMClass(false);

					$obj5 = new $cls();
					$obj5->hydrate($row, $startcol5);
					MunicipioPeer::addInstanceToPool($obj5, $key5);
				} // if $obj5 already loaded

				// Add the $obj1 (Tipodestino) to the collection in $obj5 (Municipio)
				$obj5->addTipodestino($obj1);

			} // if joined row is not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Selects a collection of Tipodestino objects pre-filled with all related objects except Pais.
	 *
	 * @param      Criteria  $criteria
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of Tipodestino objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinAllExceptPais(Criteria $criteria, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		$criteria = clone $criteria;

		// Set the correct dbName if it has not been overridden
		// $criteria->getDbName() will return the same object if not set to another value
		// so == check is okay and faster
		if ($criteria->getDbName() == Propel::getDefaultDB()) {
			$criteria->setDbName(self::DATABASE_NAME);
		}

		TipodestinoPeer::addSelectColumns($criteria);
		$startcol2 = (TipodestinoPeer::NUM_COLUMNS - TipodestinoPeer::NUM_LAZY_LOAD_COLUMNS);

		FeriaPeer::addSelectColumns($criteria);
		$startcol3 = $startcol2 + (FeriaPeer::NUM_COLUMNS - FeriaPeer::NUM_LAZY_LOAD_COLUMNS);

		EstadoPeer::addSelectColumns($criteria);
		$startcol4 = $startcol3 + (EstadoPeer::NUM_COLUMNS - EstadoPeer::NUM_LAZY_LOAD_COLUMNS);

		LibreriaPeer::addSelectColumns($criteria);
		$startcol5 = $startcol4 + (LibreriaPeer::NUM_COLUMNS - LibreriaPeer::NUM_LAZY_LOAD_COLUMNS);

		MunicipioPeer::addSelectColumns($criteria);
		$startcol6 = $startcol5 + (MunicipioPeer::NUM_COLUMNS - MunicipioPeer::NUM_LAZY_LOAD_COLUMNS);

		$criteria->addJoin(TipodestinoPeer::ID_FERIA, FeriaPeer::ID, $join_behavior);

		$criteria->addJoin(TipodestinoPeer::ID_ESTADO, EstadoPeer::ID, $join_behavior);

		$criteria->addJoin(TipodestinoPeer::ID_LIBRERIA, LibreriaPeer::ID, $join_behavior);

		$criteria->addJoin(TipodestinoPeer::ID_MUNICIPIO, MunicipioPeer::ID, $join_behavior);

		// symfony_behaviors behavior
		foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
		{
		  call_user_func($sf_hook, 'BaseTipodestinoPeer', $criteria, $con);
		}


		$stmt = BasePeer::doSelect($criteria, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = TipodestinoPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = TipodestinoPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://www.propelorm.org/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {
				$cls = TipodestinoPeer::getOMClass(false);

				$obj1 = new $cls();
				$obj1->hydrate($row);
				TipodestinoPeer::addInstanceToPool($obj1, $key1);
			} // if obj1 already loaded

				// Add objects for joined Feria rows

				$key2 = FeriaPeer::getPrimaryKeyHashFromRow($row, $startcol2);
				if ($key2 !== null) {
					$obj2 = FeriaPeer::getInstanceFromPool($key2);
					if (!$obj2) {
	
						$cls = FeriaPeer::getOMClass(false);

					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol2);
					FeriaPeer::addInstanceToPool($obj2, $key2);
				} // if $obj2 already loaded

				// Add the $obj1 (Tipodestino) to the collection in $obj2 (Feria)
				$obj2->addTipodestino($obj1);

			} // if joined row is not null

				// Add objects for joined Estado rows

				$key3 = EstadoPeer::getPrimaryKeyHashFromRow($row, $startcol3);
				if ($key3 !== null) {
					$obj3 = EstadoPeer::getInstanceFromPool($key3);
					if (!$obj3) {
	
						$cls = EstadoPeer::getOMClass(false);

					$obj3 = new $cls();
					$obj3->hydrate($row, $startcol3);
					EstadoPeer::addInstanceToPool($obj3, $key3);
				} // if $obj3 already loaded

				// Add the $obj1 (Tipodestino) to the collection in $obj3 (Estado)
				$obj3->addTipodestino($obj1);

			} // if joined row is not null

				// Add objects for joined Libreria rows

				$key4 = LibreriaPeer::getPrimaryKeyHashFromRow($row, $startcol4);
				if ($key4 !== null) {
					$obj4 = LibreriaPeer::getInstanceFromPool($key4);
					if (!$obj4) {
	
						$cls = LibreriaPeer::getOMClass(false);

					$obj4 = new $cls();
					$obj4->hydrate($row, $startcol4);
					LibreriaPeer::addInstanceToPool($obj4, $key4);
				} // if $obj4 already loaded

				// Add the $obj1 (Tipodestino) to the collection in $obj4 (Libreria)
				$obj4->addTipodestino($obj1);

			} // if joined row is not null

				// Add objects for joined Municipio rows

				$key5 = MunicipioPeer::getPrimaryKeyHashFromRow($row, $startcol5);
				if ($key5 !== null) {
					$obj5 = MunicipioPeer::getInstanceFromPool($key5);
					if (!$obj5) {
	
						$cls = MunicipioPeer::getOMClass(false);

					$obj5 = new $cls();
					$obj5->hydrate($row, $startcol5);
					MunicipioPeer::addInstanceToPool($obj5, $key5);
				} // if $obj5 already loaded

				// Add the $obj1 (Tipodestino) to the collection in $obj5 (Municipio)
				$obj5->addTipodestino($obj1);

			} // if joined row is not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Selects a collection of Tipodestino objects pre-filled with all related objects except Estado.
	 *
	 * @param      Criteria  $criteria
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of Tipodestino objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinAllExceptEstado(Criteria $criteria, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		$criteria = clone $criteria;

		// Set the correct dbName if it has not been overridden
		// $criteria->getDbName() will return the same object if not set to another value
		// so == check is okay and faster
		if ($criteria->getDbName() == Propel::getDefaultDB()) {
			$criteria->setDbName(self::DATABASE_NAME);
		}

		TipodestinoPeer::addSelectColumns($criteria);
		$startcol2 = (TipodestinoPeer::NUM_COLUMNS - TipodestinoPeer::NUM_LAZY_LOAD_COLUMNS);

		FeriaPeer::addSelectColumns($criteria);
		$startcol3 = $startcol2 + (FeriaPeer::NUM_COLUMNS - FeriaPeer::NUM_LAZY_LOAD_COLUMNS);

		PaisPeer::addSelectColumns($criteria);
		$startcol4 = $startcol3 + (PaisPeer::NUM_COLUMNS - PaisPeer::NUM_LAZY_LOAD_COLUMNS);

		LibreriaPeer::addSelectColumns($criteria);
		$startcol5 = $startcol4 + (LibreriaPeer::NUM_COLUMNS - LibreriaPeer::NUM_LAZY_LOAD_COLUMNS);

		MunicipioPeer::addSelectColumns($criteria);
		$startcol6 = $startcol5 + (MunicipioPeer::NUM_COLUMNS - MunicipioPeer::NUM_LAZY_LOAD_COLUMNS);

		$criteria->addJoin(TipodestinoPeer::ID_FERIA, FeriaPeer::ID, $join_behavior);

		$criteria->addJoin(TipodestinoPeer::ID_PAIS, PaisPeer::ID, $join_behavior);

		$criteria->addJoin(TipodestinoPeer::ID_LIBRERIA, LibreriaPeer::ID, $join_behavior);

		$criteria->addJoin(TipodestinoPeer::ID_MUNICIPIO, MunicipioPeer::ID, $join_behavior);

		// symfony_behaviors behavior
		foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
		{
		  call_user_func($sf_hook, 'BaseTipodestinoPeer', $criteria, $con);
		}


		$stmt = BasePeer::doSelect($criteria, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = TipodestinoPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = TipodestinoPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://www.propelorm.org/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {
				$cls = TipodestinoPeer::getOMClass(false);

				$obj1 = new $cls();
				$obj1->hydrate($row);
				TipodestinoPeer::addInstanceToPool($obj1, $key1);
			} // if obj1 already loaded

				// Add objects for joined Feria rows

				$key2 = FeriaPeer::getPrimaryKeyHashFromRow($row, $startcol2);
				if ($key2 !== null) {
					$obj2 = FeriaPeer::getInstanceFromPool($key2);
					if (!$obj2) {
	
						$cls = FeriaPeer::getOMClass(false);

					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol2);
					FeriaPeer::addInstanceToPool($obj2, $key2);
				} // if $obj2 already loaded

				// Add the $obj1 (Tipodestino) to the collection in $obj2 (Feria)
				$obj2->addTipodestino($obj1);

			} // if joined row is not null

				// Add objects for joined Pais rows

				$key3 = PaisPeer::getPrimaryKeyHashFromRow($row, $startcol3);
				if ($key3 !== null) {
					$obj3 = PaisPeer::getInstanceFromPool($key3);
					if (!$obj3) {
	
						$cls = PaisPeer::getOMClass(false);

					$obj3 = new $cls();
					$obj3->hydrate($row, $startcol3);
					PaisPeer::addInstanceToPool($obj3, $key3);
				} // if $obj3 already loaded

				// Add the $obj1 (Tipodestino) to the collection in $obj3 (Pais)
				$obj3->addTipodestino($obj1);

			} // if joined row is not null

				// Add objects for joined Libreria rows

				$key4 = LibreriaPeer::getPrimaryKeyHashFromRow($row, $startcol4);
				if ($key4 !== null) {
					$obj4 = LibreriaPeer::getInstanceFromPool($key4);
					if (!$obj4) {
	
						$cls = LibreriaPeer::getOMClass(false);

					$obj4 = new $cls();
					$obj4->hydrate($row, $startcol4);
					LibreriaPeer::addInstanceToPool($obj4, $key4);
				} // if $obj4 already loaded

				// Add the $obj1 (Tipodestino) to the collection in $obj4 (Libreria)
				$obj4->addTipodestino($obj1);

			} // if joined row is not null

				// Add objects for joined Municipio rows

				$key5 = MunicipioPeer::getPrimaryKeyHashFromRow($row, $startcol5);
				if ($key5 !== null) {
					$obj5 = MunicipioPeer::getInstanceFromPool($key5);
					if (!$obj5) {
	
						$cls = MunicipioPeer::getOMClass(false);

					$obj5 = new $cls();
					$obj5->hydrate($row, $startcol5);
					MunicipioPeer::addInstanceToPool($obj5, $key5);
				} // if $obj5 already loaded

				// Add the $obj1 (Tipodestino) to the collection in $obj5 (Municipio)
				$obj5->addTipodestino($obj1);

			} // if joined row is not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Selects a collection of Tipodestino objects pre-filled with all related objects except Libreria.
	 *
	 * @param      Criteria  $criteria
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of Tipodestino objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinAllExceptLibreria(Criteria $criteria, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		$criteria = clone $criteria;

		// Set the correct dbName if it has not been overridden
		// $criteria->getDbName() will return the same object if not set to another value
		// so == check is okay and faster
		if ($criteria->getDbName() == Propel::getDefaultDB()) {
			$criteria->setDbName(self::DATABASE_NAME);
		}

		TipodestinoPeer::addSelectColumns($criteria);
		$startcol2 = (TipodestinoPeer::NUM_COLUMNS - TipodestinoPeer::NUM_LAZY_LOAD_COLUMNS);

		FeriaPeer::addSelectColumns($criteria);
		$startcol3 = $startcol2 + (FeriaPeer::NUM_COLUMNS - FeriaPeer::NUM_LAZY_LOAD_COLUMNS);

		PaisPeer::addSelectColumns($criteria);
		$startcol4 = $startcol3 + (PaisPeer::NUM_COLUMNS - PaisPeer::NUM_LAZY_LOAD_COLUMNS);

		EstadoPeer::addSelectColumns($criteria);
		$startcol5 = $startcol4 + (EstadoPeer::NUM_COLUMNS - EstadoPeer::NUM_LAZY_LOAD_COLUMNS);

		MunicipioPeer::addSelectColumns($criteria);
		$startcol6 = $startcol5 + (MunicipioPeer::NUM_COLUMNS - MunicipioPeer::NUM_LAZY_LOAD_COLUMNS);

		$criteria->addJoin(TipodestinoPeer::ID_FERIA, FeriaPeer::ID, $join_behavior);

		$criteria->addJoin(TipodestinoPeer::ID_PAIS, PaisPeer::ID, $join_behavior);

		$criteria->addJoin(TipodestinoPeer::ID_ESTADO, EstadoPeer::ID, $join_behavior);

		$criteria->addJoin(TipodestinoPeer::ID_MUNICIPIO, MunicipioPeer::ID, $join_behavior);

		// symfony_behaviors behavior
		foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
		{
		  call_user_func($sf_hook, 'BaseTipodestinoPeer', $criteria, $con);
		}


		$stmt = BasePeer::doSelect($criteria, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = TipodestinoPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = TipodestinoPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://www.propelorm.org/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {
				$cls = TipodestinoPeer::getOMClass(false);

				$obj1 = new $cls();
				$obj1->hydrate($row);
				TipodestinoPeer::addInstanceToPool($obj1, $key1);
			} // if obj1 already loaded

				// Add objects for joined Feria rows

				$key2 = FeriaPeer::getPrimaryKeyHashFromRow($row, $startcol2);
				if ($key2 !== null) {
					$obj2 = FeriaPeer::getInstanceFromPool($key2);
					if (!$obj2) {
	
						$cls = FeriaPeer::getOMClass(false);

					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol2);
					FeriaPeer::addInstanceToPool($obj2, $key2);
				} // if $obj2 already loaded

				// Add the $obj1 (Tipodestino) to the collection in $obj2 (Feria)
				$obj2->addTipodestino($obj1);

			} // if joined row is not null

				// Add objects for joined Pais rows

				$key3 = PaisPeer::getPrimaryKeyHashFromRow($row, $startcol3);
				if ($key3 !== null) {
					$obj3 = PaisPeer::getInstanceFromPool($key3);
					if (!$obj3) {
	
						$cls = PaisPeer::getOMClass(false);

					$obj3 = new $cls();
					$obj3->hydrate($row, $startcol3);
					PaisPeer::addInstanceToPool($obj3, $key3);
				} // if $obj3 already loaded

				// Add the $obj1 (Tipodestino) to the collection in $obj3 (Pais)
				$obj3->addTipodestino($obj1);

			} // if joined row is not null

				// Add objects for joined Estado rows

				$key4 = EstadoPeer::getPrimaryKeyHashFromRow($row, $startcol4);
				if ($key4 !== null) {
					$obj4 = EstadoPeer::getInstanceFromPool($key4);
					if (!$obj4) {
	
						$cls = EstadoPeer::getOMClass(false);

					$obj4 = new $cls();
					$obj4->hydrate($row, $startcol4);
					EstadoPeer::addInstanceToPool($obj4, $key4);
				} // if $obj4 already loaded

				// Add the $obj1 (Tipodestino) to the collection in $obj4 (Estado)
				$obj4->addTipodestino($obj1);

			} // if joined row is not null

				// Add objects for joined Municipio rows

				$key5 = MunicipioPeer::getPrimaryKeyHashFromRow($row, $startcol5);
				if ($key5 !== null) {
					$obj5 = MunicipioPeer::getInstanceFromPool($key5);
					if (!$obj5) {
	
						$cls = MunicipioPeer::getOMClass(false);

					$obj5 = new $cls();
					$obj5->hydrate($row, $startcol5);
					MunicipioPeer::addInstanceToPool($obj5, $key5);
				} // if $obj5 already loaded

				// Add the $obj1 (Tipodestino) to the collection in $obj5 (Municipio)
				$obj5->addTipodestino($obj1);

			} // if joined row is not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Selects a collection of Tipodestino objects pre-filled with all related objects except Municipio.
	 *
	 * @param      Criteria  $criteria
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of Tipodestino objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinAllExceptMunicipio(Criteria $criteria, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		$criteria = clone $criteria;

		// Set the correct dbName if it has not been overridden
		// $criteria->getDbName() will return the same object if not set to another value
		// so == check is okay and faster
		if ($criteria->getDbName() == Propel::getDefaultDB()) {
			$criteria->setDbName(self::DATABASE_NAME);
		}

		TipodestinoPeer::addSelectColumns($criteria);
		$startcol2 = (TipodestinoPeer::NUM_COLUMNS - TipodestinoPeer::NUM_LAZY_LOAD_COLUMNS);

		FeriaPeer::addSelectColumns($criteria);
		$startcol3 = $startcol2 + (FeriaPeer::NUM_COLUMNS - FeriaPeer::NUM_LAZY_LOAD_COLUMNS);

		PaisPeer::addSelectColumns($criteria);
		$startcol4 = $startcol3 + (PaisPeer::NUM_COLUMNS - PaisPeer::NUM_LAZY_LOAD_COLUMNS);

		EstadoPeer::addSelectColumns($criteria);
		$startcol5 = $startcol4 + (EstadoPeer::NUM_COLUMNS - EstadoPeer::NUM_LAZY_LOAD_COLUMNS);

		LibreriaPeer::addSelectColumns($criteria);
		$startcol6 = $startcol5 + (LibreriaPeer::NUM_COLUMNS - LibreriaPeer::NUM_LAZY_LOAD_COLUMNS);

		$criteria->addJoin(TipodestinoPeer::ID_FERIA, FeriaPeer::ID, $join_behavior);

		$criteria->addJoin(TipodestinoPeer::ID_PAIS, PaisPeer::ID, $join_behavior);

		$criteria->addJoin(TipodestinoPeer::ID_ESTADO, EstadoPeer::ID, $join_behavior);

		$criteria->addJoin(TipodestinoPeer::ID_LIBRERIA, LibreriaPeer::ID, $join_behavior);

		// symfony_behaviors behavior
		foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
		{
		  call_user_func($sf_hook, 'BaseTipodestinoPeer', $criteria, $con);
		}


		$stmt = BasePeer::doSelect($criteria, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = TipodestinoPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = TipodestinoPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://www.propelorm.org/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {
				$cls = TipodestinoPeer::getOMClass(false);

				$obj1 = new $cls();
				$obj1->hydrate($row);
				TipodestinoPeer::addInstanceToPool($obj1, $key1);
			} // if obj1 already loaded

				// Add objects for joined Feria rows

				$key2 = FeriaPeer::getPrimaryKeyHashFromRow($row, $startcol2);
				if ($key2 !== null) {
					$obj2 = FeriaPeer::getInstanceFromPool($key2);
					if (!$obj2) {
	
						$cls = FeriaPeer::getOMClass(false);

					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol2);
					FeriaPeer::addInstanceToPool($obj2, $key2);
				} // if $obj2 already loaded

				// Add the $obj1 (Tipodestino) to the collection in $obj2 (Feria)
				$obj2->addTipodestino($obj1);

			} // if joined row is not null

				// Add objects for joined Pais rows

				$key3 = PaisPeer::getPrimaryKeyHashFromRow($row, $startcol3);
				if ($key3 !== null) {
					$obj3 = PaisPeer::getInstanceFromPool($key3);
					if (!$obj3) {
	
						$cls = PaisPeer::getOMClass(false);

					$obj3 = new $cls();
					$obj3->hydrate($row, $startcol3);
					PaisPeer::addInstanceToPool($obj3, $key3);
				} // if $obj3 already loaded

				// Add the $obj1 (Tipodestino) to the collection in $obj3 (Pais)
				$obj3->addTipodestino($obj1);

			} // if joined row is not null

				// Add objects for joined Estado rows

				$key4 = EstadoPeer::getPrimaryKeyHashFromRow($row, $startcol4);
				if ($key4 !== null) {
					$obj4 = EstadoPeer::getInstanceFromPool($key4);
					if (!$obj4) {
	
						$cls = EstadoPeer::getOMClass(false);

					$obj4 = new $cls();
					$obj4->hydrate($row, $startcol4);
					EstadoPeer::addInstanceToPool($obj4, $key4);
				} // if $obj4 already loaded

				// Add the $obj1 (Tipodestino) to the collection in $obj4 (Estado)
				$obj4->addTipodestino($obj1);

			} // if joined row is not null

				// Add objects for joined Libreria rows

				$key5 = LibreriaPeer::getPrimaryKeyHashFromRow($row, $startcol5);
				if ($key5 !== null) {
					$obj5 = LibreriaPeer::getInstanceFromPool($key5);
					if (!$obj5) {
	
						$cls = LibreriaPeer::getOMClass(false);

					$obj5 = new $cls();
					$obj5->hydrate($row, $startcol5);
					LibreriaPeer::addInstanceToPool($obj5, $key5);
				} // if $obj5 already loaded

				// Add the $obj1 (Tipodestino) to the collection in $obj5 (Libreria)
				$obj5->addTipodestino($obj1);

			} // if joined row is not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}

	/**
	 * Returns the TableMap related to this peer.
	 * This method is not needed for general use but a specific application could have a need.
	 * @return     TableMap
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function getTableMap()
	{
		return Propel::getDatabaseMap(self::DATABASE_NAME)->getTable(self::TABLE_NAME);
	}

	/**
	 * Add a TableMap instance to the database for this peer class.
	 */
	public static function buildTableMap()
	{
	  $dbMap = Propel::getDatabaseMap(BaseTipodestinoPeer::DATABASE_NAME);
	  if (!$dbMap->hasTable(BaseTipodestinoPeer::TABLE_NAME))
	  {
	    $dbMap->addTableObject(new TipodestinoTableMap());
	  }
	}

	/**
	 * The class that the Peer will make instances of.
	 *
	 * If $withPrefix is true, the returned path
	 * uses a dot-path notation which is tranalted into a path
	 * relative to a location on the PHP include_path.
	 * (e.g. path.to.MyClass -> 'path/to/MyClass.php')
	 *
	 * @param      boolean $withPrefix Whether or not to return the path with the class name
	 * @return     string path.to.ClassName
	 */
	public static function getOMClass($withPrefix = true)
	{
		return $withPrefix ? TipodestinoPeer::CLASS_DEFAULT : TipodestinoPeer::OM_CLASS;
	}

	/**
	 * Method perform an INSERT on the database, given a Tipodestino or Criteria object.
	 *
	 * @param      mixed $values Criteria or Tipodestino object containing data that is used to create the INSERT statement.
	 * @param      PropelPDO $con the PropelPDO connection to use
	 * @return     mixed The new primary key.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doInsert($values, PropelPDO $con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(TipodestinoPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		if ($values instanceof Criteria) {
			$criteria = clone $values; // rename for clarity
		} else {
			$criteria = $values->buildCriteria(); // build Criteria from Tipodestino object
		}

		if ($criteria->containsKey(TipodestinoPeer::ID) && $criteria->keyContainsValue(TipodestinoPeer::ID) ) {
			throw new PropelException('Cannot insert a value for auto-increment primary key ('.TipodestinoPeer::ID.')');
		}


		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		try {
			// use transaction because $criteria could contain info
			// for more than one table (I guess, conceivably)
			$con->beginTransaction();
			$pk = BasePeer::doInsert($criteria, $con);
			$con->commit();
		} catch(PropelException $e) {
			$con->rollBack();
			throw $e;
		}

		return $pk;
	}

	/**
	 * Method perform an UPDATE on the database, given a Tipodestino or Criteria object.
	 *
	 * @param      mixed $values Criteria or Tipodestino object containing data that is used to create the UPDATE statement.
	 * @param      PropelPDO $con The connection to use (specify PropelPDO connection object to exert more control over transactions).
	 * @return     int The number of affected rows (if supported by underlying database driver).
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doUpdate($values, PropelPDO $con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(TipodestinoPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		$selectCriteria = new Criteria(self::DATABASE_NAME);

		if ($values instanceof Criteria) {
			$criteria = clone $values; // rename for clarity

			$comparison = $criteria->getComparison(TipodestinoPeer::ID);
			$value = $criteria->remove(TipodestinoPeer::ID);
			if ($value) {
				$selectCriteria->add(TipodestinoPeer::ID, $value, $comparison);
			} else {
				$selectCriteria->setPrimaryTableName(TipodestinoPeer::TABLE_NAME);
			}

		} else { // $values is Tipodestino object
			$criteria = $values->buildCriteria(); // gets full criteria
			$selectCriteria = $values->buildPkeyCriteria(); // gets criteria w/ primary key(s)
		}

		// set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		return BasePeer::doUpdate($selectCriteria, $criteria, $con);
	}

	/**
	 * Method to DELETE all rows from the tipodestino table.
	 *
	 * @return     int The number of affected rows (if supported by underlying database driver).
	 */
	public static function doDeleteAll($con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(TipodestinoPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		$affectedRows = 0; // initialize var to track total num of affected rows
		try {
			// use transaction because $criteria could contain info
			// for more than one table or we could emulating ON DELETE CASCADE, etc.
			$con->beginTransaction();
			$affectedRows += BasePeer::doDeleteAll(TipodestinoPeer::TABLE_NAME, $con, TipodestinoPeer::DATABASE_NAME);
			// Because this db requires some delete cascade/set null emulation, we have to
			// clear the cached instance *after* the emulation has happened (since
			// instances get re-added by the select statement contained therein).
			TipodestinoPeer::clearInstancePool();
			TipodestinoPeer::clearRelatedInstancePool();
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Method perform a DELETE on the database, given a Tipodestino or Criteria object OR a primary key value.
	 *
	 * @param      mixed $values Criteria or Tipodestino object or primary key or array of primary keys
	 *              which is used to create the DELETE statement
	 * @param      PropelPDO $con the connection to use
	 * @return     int 	The number of affected rows (if supported by underlying database driver).  This includes CASCADE-related rows
	 *				if supported by native driver or if emulated using Propel.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	 public static function doDelete($values, PropelPDO $con = null)
	 {
		if ($con === null) {
			$con = Propel::getConnection(TipodestinoPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		if ($values instanceof Criteria) {
			// invalidate the cache for all objects of this type, since we have no
			// way of knowing (without running a query) what objects should be invalidated
			// from the cache based on this Criteria.
			TipodestinoPeer::clearInstancePool();
			// rename for clarity
			$criteria = clone $values;
		} elseif ($values instanceof Tipodestino) { // it's a model object
			// invalidate the cache for this single object
			TipodestinoPeer::removeInstanceFromPool($values);
			// create criteria based on pk values
			$criteria = $values->buildPkeyCriteria();
		} else { // it's a primary key, or an array of pks
			$criteria = new Criteria(self::DATABASE_NAME);
			$criteria->add(TipodestinoPeer::ID, (array) $values, Criteria::IN);
			// invalidate the cache for this object(s)
			foreach ((array) $values as $singleval) {
				TipodestinoPeer::removeInstanceFromPool($singleval);
			}
		}

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		$affectedRows = 0; // initialize var to track total num of affected rows

		try {
			// use transaction because $criteria could contain info
			// for more than one table or we could emulating ON DELETE CASCADE, etc.
			$con->beginTransaction();
			
			$affectedRows += BasePeer::doDelete($criteria, $con);
			TipodestinoPeer::clearRelatedInstancePool();
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Validates all modified columns of given Tipodestino object.
	 * If parameter $columns is either a single column name or an array of column names
	 * than only those columns are validated.
	 *
	 * NOTICE: This does not apply to primary or foreign keys for now.
	 *
	 * @param      Tipodestino $obj The object to validate.
	 * @param      mixed $cols Column name or array of column names.
	 *
	 * @return     mixed TRUE if all columns are valid or the error message of the first invalid column.
	 */
	public static function doValidate(Tipodestino $obj, $cols = null)
	{
		$columns = array();

		if ($cols) {
			$dbMap = Propel::getDatabaseMap(TipodestinoPeer::DATABASE_NAME);
			$tableMap = $dbMap->getTable(TipodestinoPeer::TABLE_NAME);

			if (! is_array($cols)) {
				$cols = array($cols);
			}

			foreach ($cols as $colName) {
				if ($tableMap->containsColumn($colName)) {
					$get = 'get' . $tableMap->getColumn($colName)->getPhpName();
					$columns[$colName] = $obj->$get();
				}
			}
		} else {

		}

		return BasePeer::doValidate(TipodestinoPeer::DATABASE_NAME, TipodestinoPeer::TABLE_NAME, $columns);
	}

	/**
	 * Retrieve a single object by pkey.
	 *
	 * @param      string $pk the primary key.
	 * @param      PropelPDO $con the connection to use
	 * @return     Tipodestino
	 */
	public static function retrieveByPK($pk, PropelPDO $con = null)
	{

		if (null !== ($obj = TipodestinoPeer::getInstanceFromPool((string) $pk))) {
			return $obj;
		}

		if ($con === null) {
			$con = Propel::getConnection(TipodestinoPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria = new Criteria(TipodestinoPeer::DATABASE_NAME);
		$criteria->add(TipodestinoPeer::ID, $pk);

		$v = TipodestinoPeer::doSelect($criteria, $con);

		return !empty($v) > 0 ? $v[0] : null;
	}

	/**
	 * Retrieve multiple objects by pkey.
	 *
	 * @param      array $pks List of primary keys
	 * @param      PropelPDO $con the connection to use
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function retrieveByPKs($pks, PropelPDO $con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(TipodestinoPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$objs = null;
		if (empty($pks)) {
			$objs = array();
		} else {
			$criteria = new Criteria(TipodestinoPeer::DATABASE_NAME);
			$criteria->add(TipodestinoPeer::ID, $pks, Criteria::IN);
			$objs = TipodestinoPeer::doSelect($criteria, $con);
		}
		return $objs;
	}

	// symfony behavior
	
	/**
	 * Returns an array of arrays that contain columns in each unique index.
	 *
	 * @return array
	 */
	static public function getUniqueColumnNames()
	{
	  return array();
	}

	// symfony_behaviors behavior
	
	/**
	 * Returns the name of the hook to call from inside the supplied method.
	 *
	 * @param string $method The calling method
	 *
	 * @return string A hook name for {@link sfMixer}
	 *
	 * @throws LogicException If the method name is not recognized
	 */
	static private function getMixerPreSelectHook($method)
	{
	  if (preg_match('/^do(Select|Count)(Join(All(Except)?)?|Stmt)?/', $method, $match))
	  {
	    return sprintf('BaseTipodestinoPeer:%s:%1$s', 'Count' == $match[1] ? 'doCount' : $match[0]);
	  }
	
	  throw new LogicException(sprintf('Unrecognized function "%s"', $method));
	}

} // BaseTipodestinoPeer

// This is the static code needed to register the TableMap for this table with the main Propel class.
//
BaseTipodestinoPeer::buildTableMap();

