<?php



/**
 * Skeleton subclass for performing query and update operations on the 'estado' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.5.6 on:
 *
 * Mon Feb 25 16:36:35 2013
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class EstadoPeer extends BaseEstadoPeer {

} // EstadoPeer
