<?php



/**
 * Skeleton subclass for performing query and update operations on the 'ponente' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.5.6 on:
 *
 * Sun Feb 17 11:51:26 2013
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class PonentePeer extends BasePonentePeer {

} // PonentePeer
